-- ============================================================================
-- ISALAB · Migración 0001 — Schema inicial (Firebird 5.0, dialecto 3)
-- Ejecutada desde Rust al primer arranque (src-tauri/src/db/migrations.rs).
-- Convenciones:
--   * IDs por GENERATOR + trigger BEFORE INSERT (IF NEW.ID IS NULL).
--   * DSQL parametrizado en la app; aquí SOLO DDL/DML estructurado.
--   * DOMAINs para tipos reutilizables (documentos, teléfono, textos, etc.).
--   * EVENT_LOG + POST_EVENT para notificar al frontend cambios de muestras.
-- ============================================================================

-- ============================== DOMAINS =====================================
CREATE DOMAIN D_PK AS INTEGER;
CREATE DOMAIN D_NAME AS VARCHAR(80) CHARACTER SET UTF8;
CREATE DOMAIN D_DOC_TYPE AS VARCHAR(4) CHARACTER SET UTF8;
CREATE DOMAIN D_DOC_NUMBER AS VARCHAR(20) CHARACTER SET UTF8;
CREATE DOMAIN D_PHONE AS VARCHAR(20) CHARACTER SET UTF8;
CREATE DOMAIN D_EMAIL AS VARCHAR(120) CHARACTER SET UTF8;
CREATE DOMAIN D_ADDRESS AS VARCHAR(200) CHARACTER SET UTF8;
CREATE DOMAIN D_CITY AS VARCHAR(80) CHARACTER SET UTF8;
CREATE DOMAIN D_CODE AS VARCHAR(20) CHARACTER SET UTF8;
-- 2000 chars UTF8 (max ~8KB/columna) para que tablas con varias
-- columnas de texto quepan en el límite de fila de Firebird (~64KB).
CREATE DOMAIN D_TEXT AS VARCHAR(2000) CHARACTER SET UTF8;
CREATE DOMAIN D_NOTES AS VARCHAR(4000) CHARACTER SET UTF8;
CREATE DOMAIN D_AMOUNT AS NUMERIC(12, 2);
CREATE DOMAIN D_PERCENT AS NUMERIC(5, 2);
CREATE DOMAIN D_STATUS AS VARCHAR(20) CHARACTER SET UTF8;
CREATE DOMAIN D_SEX AS CHAR(1) CHARACTER SET UTF8;
CREATE DOMAIN D_TS AS TIMESTAMP;
CREATE DOMAIN D_DATE AS DATE;
CREATE DOMAIN D_VALUE AS DOUBLE PRECISION;

-- ===================== TABLA DE EVENTOS (NOTIFICACIONES UI) ================
-- NOTA: SCHEMA_MIGRATIONS la crea el runner de migraciones (db/migrations.rs).
CREATE TABLE EVENT_LOG (
    ID         D_PK NOT NULL PRIMARY KEY,
    EVENT_NAME VARCHAR(40) NOT NULL,
    REF_ID     INTEGER,
    PATIENT_ID INTEGER,
    STATUS     D_STATUS,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE GENERATOR GEN_EVENT_LOG_ID;

-- ============================== CATÁLOGOS ===================================
CREATE TABLE SPECIES (
    ID        D_PK NOT NULL PRIMARY KEY,
    CODE      D_CODE NOT NULL UNIQUE,
    NAME      D_NAME NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE GENERATOR GEN_SPECIES_ID;

CREATE TABLE BREEDS (
    ID         D_PK NOT NULL PRIMARY KEY,
    SPECIES_ID D_PK NOT NULL REFERENCES SPECIES (ID) ON DELETE CASCADE,
    NAME       D_NAME NOT NULL,
    IS_ACTIVE  BOOLEAN DEFAULT TRUE NOT NULL,
    UNIQUE (SPECIES_ID, NAME)
);
CREATE GENERATOR GEN_BREEDS_ID;

CREATE TABLE SAMPLE_TYPES (
    ID        D_PK NOT NULL PRIMARY KEY,
    CODE      D_CODE NOT NULL UNIQUE,
    NAME      D_NAME NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE GENERATOR GEN_SAMPLE_TYPES_ID;

CREATE TABLE ANALYTES (
    ID          D_PK NOT NULL PRIMARY KEY,
    CODE        D_CODE NOT NULL UNIQUE,
    NAME        D_NAME NOT NULL,
    UNIT        VARCHAR(20) CHARACTER SET UTF8,
    METHOD      D_NAME,
    DESCRIPTION D_TEXT,
    IS_ACTIVE   BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE GENERATOR GEN_ANALYTES_ID;

CREATE TABLE VACCINE_TYPES (
    ID        D_PK NOT NULL PRIMARY KEY,
    CODE      D_CODE NOT NULL UNIQUE,
    NAME      D_NAME NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE GENERATOR GEN_VACCINE_TYPES_ID;

-- ===================== PROPIETARIOS Y PACIENTES =============================
CREATE TABLE OWNERS (
    ID              D_PK NOT NULL PRIMARY KEY,
    DOCUMENT_TYPE   D_DOC_TYPE NOT NULL CHECK (DOCUMENT_TYPE IN ('CC', 'TI', 'CE', 'NIT', 'PA')),
    DOCUMENT_NUMBER D_DOC_NUMBER NOT NULL,
    FULL_NAME       D_NAME NOT NULL,
    PHONE           D_PHONE,
    EMAIL           D_EMAIL,
    ADDRESS         D_ADDRESS,
    CITY            D_CITY,
    NOTES           D_NOTES,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (DOCUMENT_TYPE, DOCUMENT_NUMBER)
);
CREATE GENERATOR GEN_OWNERS_ID;

CREATE TABLE PATIENTS (
    ID         D_PK NOT NULL PRIMARY KEY,
    OWNER_ID   D_PK NOT NULL REFERENCES OWNERS (ID),
    SPECIES_ID D_PK NOT NULL REFERENCES SPECIES (ID),
    BREED_ID   D_PK REFERENCES BREEDS (ID) ON DELETE SET NULL,
    NAME       D_NAME NOT NULL,
    SEX        D_SEX NOT NULL CHECK (SEX IN ('M', 'F')),
    BIRTH_DATE D_DATE,
    NEUTERED   BOOLEAN DEFAULT FALSE NOT NULL,
    COLOR      D_NAME,
    MICROCHIP  VARCHAR(30) CHARACTER SET UTF8 UNIQUE,
    ACTIVE     BOOLEAN DEFAULT TRUE NOT NULL,
    NOTES      D_NOTES,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE GENERATOR GEN_PATIENTS_ID;

-- ============================== USUARIOS ====================================
CREATE TABLE USERS (
    ID                   D_PK NOT NULL PRIMARY KEY,
    USERNAME             VARCHAR(40) CHARACTER SET UTF8 NOT NULL UNIQUE,
    FULL_NAME            D_NAME NOT NULL,
    ROLE                 D_STATUS NOT NULL CHECK (ROLE IN ('ADMIN', 'VETERINARIO', 'AUXILIAR')),
    PASSWORD_HASH        VARCHAR(100) CHARACTER SET UTF8,
    MUST_CHANGE_PASSWORD BOOLEAN DEFAULT TRUE NOT NULL,
    ACTIVE               BOOLEAN DEFAULT TRUE NOT NULL,
    CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE GENERATOR GEN_USERS_ID;

-- ============================ CONSULTAS =====================================
CREATE TABLE CONSULTATIONS (
    ID                 D_PK NOT NULL PRIMARY KEY,
    PATIENT_ID         D_PK NOT NULL REFERENCES PATIENTS (ID) ON DELETE CASCADE,
    VETERINARIAN_ID    D_PK REFERENCES USERS (ID) ON DELETE SET NULL,
    CONSULTATION_DATE  TIMESTAMP NOT NULL,
    REASON             D_TEXT NOT NULL,
    ANAMNESIS          D_TEXT,
    PHYSICAL_EXAM      D_TEXT,
    DIAGNOSIS          D_TEXT,
    TREATMENT_PLAN     D_TEXT,
    STATUS             D_STATUS DEFAULT 'PENDIENTE' NOT NULL
                       CHECK (STATUS IN ('PENDIENTE', 'COMPLETADA', 'CANCELADA')),
    CREATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE GENERATOR GEN_CONSULTATIONS_ID;

-- ====================== MUESTRAS Y RESULTADOS ===============================
CREATE TABLE SAMPLES (
    ID             D_PK NOT NULL PRIMARY KEY,
    CODE           D_CODE NOT NULL UNIQUE,
    PATIENT_ID     D_PK NOT NULL REFERENCES PATIENTS (ID) ON DELETE CASCADE,
    SAMPLE_TYPE_ID D_PK NOT NULL REFERENCES SAMPLE_TYPES (ID),
    RECEIVED_AT    TIMESTAMP NOT NULL,
    STATUS         D_STATUS DEFAULT 'RECIBIDA' NOT NULL
                   CHECK (STATUS IN ('RECIBIDA', 'EN_PROCESO', 'FINALIZADA', 'ANULADA')),
    COLLECTED_BY   D_NAME,
    NOTES          D_NOTES,
    CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE GENERATOR GEN_SAMPLES_ID;

CREATE TABLE REFERENCE_RANGES (
    ID            D_PK NOT NULL PRIMARY KEY,
    ANALYTE_ID    D_PK NOT NULL REFERENCES ANALYTES (ID) ON DELETE CASCADE,
    SPECIES_ID    D_PK NOT NULL REFERENCES SPECIES (ID) ON DELETE CASCADE,
    SEX           D_SEX CHECK (SEX IN ('M', 'F')),   -- NULL = ambos sexos
    AGE_MIN_MONTHS INTEGER NOT NULL,
    AGE_MAX_MONTHS INTEGER NOT NULL,
    MIN_VALUE     D_VALUE NOT NULL,
    MAX_VALUE     D_VALUE NOT NULL,
    CRITICAL_MIN  D_VALUE,
    CRITICAL_MAX  D_VALUE,
    NOTES         D_NOTES,
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS),
    CHECK (AGE_MAX_MONTHS >= AGE_MIN_MONTHS),
    CHECK (MAX_VALUE >= MIN_VALUE)
);
CREATE GENERATOR GEN_REFERENCE_RANGES_ID;

CREATE TABLE LAB_RESULTS (
    ID                D_PK NOT NULL PRIMARY KEY,
    SAMPLE_ID         D_PK NOT NULL REFERENCES SAMPLES (ID) ON DELETE CASCADE,
    ANALYTE_ID        D_PK NOT NULL REFERENCES ANALYTES (ID),
    REFERENCE_RANGE_ID D_PK REFERENCES REFERENCE_RANGES (ID) ON DELETE SET NULL,
    RESULT_VALUE      D_VALUE NOT NULL,
    STATUS            D_STATUS NOT NULL CHECK (STATUS IN ('BAJO', 'NORMAL', 'ALTO', 'SIN_RANGO')),
    NOTES             D_NOTES,
    ANALYZED_BY       D_PK REFERENCES USERS (ID) ON DELETE SET NULL,
    ANALYZED_AT       TIMESTAMP,
    CREATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (SAMPLE_ID, ANALYTE_ID)
);
CREATE GENERATOR GEN_LAB_RESULTS_ID;

-- ============================ VACUNACIÓN ====================================
CREATE TABLE VACCINES (
    ID              D_PK NOT NULL PRIMARY KEY,
    PATIENT_ID      D_PK NOT NULL REFERENCES PATIENTS (ID) ON DELETE CASCADE,
    VACCINE_TYPE_ID D_PK REFERENCES VACCINE_TYPES (ID) ON DELETE SET NULL,
    VACCINE_NAME    D_NAME NOT NULL,
    DOSE            VARCHAR(30) CHARACTER SET UTF8,
    ADMINISTERED_AT TIMESTAMP NOT NULL,
    NEXT_DOSE_AT    D_DATE,
    LOT             VARCHAR(40) CHARACTER SET UTF8,
    MANUFACTURER    D_NAME,
    VETERINARIAN_ID D_PK REFERENCES USERS (ID) ON DELETE SET NULL,
    NOTES           D_NOTES,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE GENERATOR GEN_VACCINES_ID;

-- ============================ FACTURACIÓN ===================================
CREATE TABLE INVOICES (
    ID              D_PK NOT NULL PRIMARY KEY,
    INVOICE_NUMBER  D_CODE NOT NULL UNIQUE,
    PATIENT_ID      D_PK REFERENCES PATIENTS (ID) ON DELETE SET NULL,
    OWNER_ID        D_PK NOT NULL REFERENCES OWNERS (ID),
    CONSULTATION_ID D_PK REFERENCES CONSULTATIONS (ID) ON DELETE SET NULL,
    ISSUE_DATE      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SUBTOTAL        D_AMOUNT DEFAULT 0 NOT NULL,
    TAX_RATE        D_PERCENT DEFAULT 0 NOT NULL,
    TAX_AMOUNT      D_AMOUNT DEFAULT 0 NOT NULL,
    TOTAL           D_AMOUNT DEFAULT 0 NOT NULL,
    STATUS          D_STATUS DEFAULT 'EMITIDA' NOT NULL
                    CHECK (STATUS IN ('EMITIDA', 'PAGADA', 'ANULADA')),
    PAYMENT_METHOD  VARCHAR(30) CHARACTER SET UTF8,
    NOTES           D_NOTES,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE GENERATOR GEN_INVOICES_ID;

CREATE TABLE INVOICE_ITEMS (
    ID          D_PK NOT NULL PRIMARY KEY,
    INVOICE_ID  D_PK NOT NULL REFERENCES INVOICES (ID) ON DELETE CASCADE,
    DESCRIPTION VARCHAR(200) CHARACTER SET UTF8 NOT NULL,
    QUANTITY    INTEGER DEFAULT 1 NOT NULL CHECK (QUANTITY > 0),
    UNIT_PRICE  D_AMOUNT NOT NULL,
    LINE_TOTAL  D_AMOUNT NOT NULL
);
CREATE GENERATOR GEN_INVOICE_ITEMS_ID;

-- ========================= CONFIGURACIÓN ====================================
CREATE TABLE CLINIC_SETTINGS (
    KEY_NAME    VARCHAR(60) CHARACTER SET UTF8 NOT NULL PRIMARY KEY,
    VALUE_TEXT  VARCHAR(500) CHARACTER SET UTF8,
    DESCRIPTION VARCHAR(200) CHARACTER SET UTF8
);

-- ============================= GENERATORS ===================================
-- (los generadores de dominio ya están junto a cada tabla)

-- ===================== TRIGGERS DE AUTOINCREMENTO ============================
SET TERM ^ ;

CREATE TRIGGER BI_SPECIES FOR SPECIES BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_SPECIES_ID, 1);
END^

CREATE TRIGGER BI_BREEDS FOR BREEDS BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_BREEDS_ID, 1);
END^

CREATE TRIGGER BI_SAMPLE_TYPES FOR SAMPLE_TYPES BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_SAMPLE_TYPES_ID, 1);
END^

CREATE TRIGGER BI_ANALYTES FOR ANALYTES BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_ANALYTES_ID, 1);
END^

CREATE TRIGGER BI_VACCINE_TYPES FOR VACCINE_TYPES BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_VACCINE_TYPES_ID, 1);
END^

CREATE TRIGGER BI_OWNERS FOR OWNERS BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_OWNERS_ID, 1);
END^

CREATE TRIGGER BI_PATIENTS FOR PATIENTS BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_PATIENTS_ID, 1);
END^

CREATE TRIGGER BI_USERS FOR USERS BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_USERS_ID, 1);
END^

CREATE TRIGGER BI_CONSULTATIONS FOR CONSULTATIONS BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_CONSULTATIONS_ID, 1);
END^

-- Muestra: genera el código M-YYYY-NNNN vinculado al ID asignado
CREATE TRIGGER BI_SAMPLES FOR SAMPLES BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_SAMPLES_ID, 1);
    IF (NEW.CODE IS NULL) THEN
        NEW.CODE = 'M-' || EXTRACT(YEAR FROM CURRENT_TIMESTAMP) || '-' ||
                   LPAD(NEW.ID, 4, '0');
END^

CREATE TRIGGER BI_REFERENCE_RANGES FOR REFERENCE_RANGES BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_REFERENCE_RANGES_ID, 1);
END^

CREATE TRIGGER BI_LAB_RESULTS FOR LAB_RESULTS BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_LAB_RESULTS_ID, 1);
END^

CREATE TRIGGER BI_VACCINES FOR VACCINES BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_VACCINES_ID, 1);
END^

CREATE TRIGGER BI_INVOICES FOR INVOICES BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_INVOICES_ID, 1);
    IF (NEW.INVOICE_NUMBER IS NULL) THEN
        NEW.INVOICE_NUMBER = 'FAC-' || LPAD(NEW.ID, 6, '0');
END^

CREATE TRIGGER BI_INVOICE_ITEMS FOR INVOICE_ITEMS BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_INVOICE_ITEMS_ID, 1);
END^

CREATE TRIGGER BI_EVENT_LOG FOR EVENT_LOG BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_EVENT_LOG_ID, 1);
END^

-- ============ TRIGGERS DE EVENTOS (Firebird Events → frontend) ==============
-- Se notifica al frontend cuando cambia el estado de una muestra o se cargan
-- resultados, garantizando trazabilidad en tiempo real.

CREATE TRIGGER AI_SAMPLES FOR SAMPLES AFTER INSERT OR UPDATE AS
BEGIN
    INSERT INTO EVENT_LOG (EVENT_NAME, REF_ID, PATIENT_ID, STATUS)
    VALUES ('SAMPLE_CHANGED', NEW.ID, NEW.PATIENT_ID, NEW.STATUS);
    POST_EVENT 'SAMPLE_CHANGED';
END^

CREATE TRIGGER AI_LAB_RESULTS FOR LAB_RESULTS AFTER INSERT OR UPDATE AS
BEGIN
    INSERT INTO EVENT_LOG (EVENT_NAME, REF_ID, PATIENT_ID, STATUS)
    VALUES ('LAB_RESULT_CHANGED',
            NEW.SAMPLE_ID,
            (SELECT FIRST 1 PATIENT_ID FROM SAMPLES WHERE ID = NEW.SAMPLE_ID),
            NEW.STATUS);
    POST_EVENT 'LAB_RESULT_CHANGED';
END^

-- ==================== STORED PROCEDURES (LÓGICA CLÍNICA) ====================
-- Encuentra el valor de referencia más específico para
-- (analito, especie, sexo, edad). Prioriza rango con sexo exacto.
CREATE PROCEDURE SP_FIND_REFERENCE_RANGE (
    P_ANALYTE_ID  INTEGER,
    P_SPECIES_ID  INTEGER,
    P_SEX         CHAR(1),
    P_AGE_MONTHS  INTEGER
) RETURNS (
    RR_ID         INTEGER,
    MIN_VALUE     DOUBLE PRECISION,
    MAX_VALUE     DOUBLE PRECISION,
    CRITICAL_MIN  DOUBLE PRECISION,
    CRITICAL_MAX  DOUBLE PRECISION
) AS
BEGIN
    SELECT FIRST 1 rr.ID, rr.MIN_VALUE, rr.MAX_VALUE, rr.CRITICAL_MIN, rr.CRITICAL_MAX
    FROM REFERENCE_RANGES rr
    WHERE rr.ANALYTE_ID = :P_ANALYTE_ID
      AND rr.SPECIES_ID = :P_SPECIES_ID
      AND :P_AGE_MONTHS BETWEEN rr.AGE_MIN_MONTHS AND rr.AGE_MAX_MONTHS
      AND (rr.SEX IS NULL OR rr.SEX = :P_SEX)
    ORDER BY CASE WHEN rr.SEX = :P_SEX THEN 0 ELSE 1 END,
             rr.AGE_MIN_MONTHS DESC
    INTO :RR_ID, :MIN_VALUE, :MAX_VALUE, :CRITICAL_MIN, :CRITICAL_MAX;
    SUSPEND;
END^

-- Valida un resultado analítico contra los rangos de referencia de la especie,
-- sexo y edad del paciente asociado a la muestra. Devuelve el estado clínico.
CREATE PROCEDURE SP_VALIDATE_ANALYTICAL_RESULT (
    P_SAMPLE_ID   INTEGER,
    P_ANALYTE_ID  INTEGER,
    P_VALUE       DOUBLE PRECISION
) RETURNS (
    RR_ID   INTEGER,
    STATUS  VARCHAR(10)
) AS
DECLARE VARIABLE V_SPECIES_ID  INTEGER;
DECLARE VARIABLE V_SEX         CHAR(1);
DECLARE VARIABLE V_AGE_MONTHS  INTEGER;
DECLARE VARIABLE V_MIN         DOUBLE PRECISION;
DECLARE VARIABLE V_MAX         DOUBLE PRECISION;
BEGIN
    SELECT FIRST 1 pa.SPECIES_ID, pa.SEX,
           COALESCE(CAST(DATEDIFF(MONTH, pa.BIRTH_DATE, CURRENT_TIMESTAMP) AS INTEGER), 0)
    FROM SAMPLES sa
    JOIN PATIENTS pa ON pa.ID = sa.PATIENT_ID
    WHERE sa.ID = :P_SAMPLE_ID
    INTO :V_SPECIES_ID, :V_SEX, :V_AGE_MONTHS;

    IF (:V_SPECIES_ID IS NULL) THEN
    BEGIN
        RR_ID  = NULL;
        STATUS = 'SIN_RANGO';
        SUSPEND;
        EXIT;
    END

    SELECT RR_ID, MIN_VALUE, MAX_VALUE
    FROM SP_FIND_REFERENCE_RANGE(:P_ANALYTE_ID, :V_SPECIES_ID, :V_SEX, :V_AGE_MONTHS)
    INTO :RR_ID, :V_MIN, :V_MAX;

    IF (:RR_ID IS NULL) THEN
    BEGIN
        STATUS = 'SIN_RANGO';
        SUSPEND;
        EXIT;
    END

    IF (:P_VALUE < :V_MIN) THEN
        STATUS = 'BAJO';
    ELSE IF (:P_VALUE > :V_MAX) THEN
        STATUS = 'ALTO';
    ELSE
        STATUS = 'NORMAL';

    SUSPEND;
END^

SET TERM ; ^
