-- ============================================================================
-- ISALAB · Migración 0002 — Catálogo inicial (semilla)
-- Especies multiespecie, razas, tipos de muestra, vacunas, analitos y
-- valores de referencia por especie + edad + sexo (Colombia).
-- ============================================================================

-- ============================== ESPECIES ====================================
INSERT INTO SPECIES (ID, CODE, NAME) VALUES (1,  'CAN', 'Canino');
INSERT INTO SPECIES (ID, CODE, NAME) VALUES (2,  'FEL', 'Felino');
INSERT INTO SPECIES (ID, CODE, NAME) VALUES (3,  'EQU', 'Equino');
INSERT INTO SPECIES (ID, CODE, NAME) VALUES (4,  'BOV', 'Bovino');
INSERT INTO SPECIES (ID, CODE, NAME) VALUES (5,  'OVI', 'Ovino');
INSERT INTO SPECIES (ID, CODE, NAME) VALUES (6,  'CAP', 'Caprino');
INSERT INTO SPECIES (ID, CODE, NAME) VALUES (7,  'POR', 'Porcino');
INSERT INTO SPECIES (ID, CODE, NAME) VALUES (8,  'AVE', 'Aves');
INSERT INTO SPECIES (ID, CODE, NAME) VALUES (9,  'EXO', 'Exóticos');

-- =============================== RAZAS ======================================
-- Canino
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (1, 1, 'Labrador Retriever');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (2, 1, 'Golden Retriever');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (3, 1, 'Pastor Alemán');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (4, 1, 'Poodle');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (5, 1, 'Beagle');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (6, 1, 'Bulldog Francés');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (7, 1, 'Chihuahua');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (8, 1, 'Pitbull');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (9, 1, 'Criollo / Mestizo');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (10, 1, 'Otra');
-- Felino
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (11, 2, 'Siamés');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (12, 2, 'Persa');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (13, 2, 'Maine Coon');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (14, 2, 'Sphynx');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (15, 2, 'Bengalí');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (16, 2, 'Angora');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (17, 2, 'Criollo / Mestizo');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (18, 2, 'Otra');
-- Equino
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (19, 3, 'Criollo Colombiano');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (20, 3, 'Paso Fino');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (21, 3, 'Pura Sangre Inglés');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (22, 3, 'Cuarto de Milla');
-- Bovino
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (23, 4, 'Holstein');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (24, 4, 'Cebú Brahman');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (25, 4, 'Gyr');
-- Ovino
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (26, 5, 'Dorper');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (27, 5, 'Hampshire');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (28, 5, 'Criollo');
-- Caprino
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (29, 6, 'Alpino Francés');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (30, 6, 'Saanen');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (31, 6, 'Criollo');
-- Porcino
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (32, 7, 'Yorkshire');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (33, 7, 'Landrace');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (34, 7, 'Duroc');
-- Aves
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (35, 8, 'Pollo de engorde');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (36, 8, 'Gallina ponedora');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (37, 8, 'Psitácidas (loros)');
-- Exóticos
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (38, 9, 'Conejo');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (39, 9, 'Hurón');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (40, 9, 'Cobayo');
INSERT INTO BREEDS (ID, SPECIES_ID, NAME) VALUES (41, 9, 'Hámster');

-- ============================ TIPOS DE MUESTRA ==============================
INSERT INTO SAMPLE_TYPES (ID, CODE, NAME) VALUES (1, 'SANGRE', 'Sangre total (EDTA)');
INSERT INTO SAMPLE_TYPES (ID, CODE, NAME) VALUES (2, 'SUERO', 'Suero');
INSERT INTO SAMPLE_TYPES (ID, CODE, NAME) VALUES (3, 'PLASMA', 'Plasma');
INSERT INTO SAMPLE_TYPES (ID, CODE, NAME) VALUES (4, 'ORINA', 'Orina');
INSERT INTO SAMPLE_TYPES (ID, CODE, NAME) VALUES (5, 'HECES', 'Heces');
INSERT INTO SAMPLE_TYPES (ID, CODE, NAME) VALUES (6, 'RASPADO', 'Raspado cutáneo');
INSERT INTO SAMPLE_TYPES (ID, CODE, NAME) VALUES (7, 'EFUSION', 'Líquido de efusión');
INSERT INTO SAMPLE_TYPES (ID, CODE, NAME) VALUES (8, 'PELO', 'Pelo');
INSERT INTO SAMPLE_TYPES (ID, CODE, NAME) VALUES (9, 'BIOPSIA', 'Biopsia');
INSERT INTO SAMPLE_TYPES (ID, CODE, NAME) VALUES (10, 'FROTIS', 'Frotis');

-- ============================== VACUNAS =====================================
INSERT INTO VACCINE_TYPES (ID, CODE, NAME) VALUES (1, 'RABIA', 'Rabia');
INSERT INTO VACCINE_TYPES (ID, CODE, NAME) VALUES (2, 'POLI_CANINA', 'Polivalente canina (M2)');
INSERT INTO VACCINE_TYPES (ID, CODE, NAME) VALUES (3, 'POLI_FELINA', 'Polivalente felina (TCRP)');
INSERT INTO VACCINE_TYPES (ID, CODE, NAME) VALUES (4, 'LEPTO', 'Leptospirosis');
INSERT INTO VACCINE_TYPES (ID, CODE, NAME) VALUES (5, 'TOS_PERRERAS', 'Tos de las perreras');
INSERT INTO VACCINE_TYPES (ID, CODE, NAME) VALUES (6, 'LEUCEMIA_FELINA', 'Leucemia felina (FeLV)');
INSERT INTO VACCINE_TYPES (ID, CODE, NAME) VALUES (7, 'PARVOVIRUS', 'Parvovirus');
INSERT INTO VACCINE_TYPES (ID, CODE, NAME) VALUES (8, 'MOQUILLO', 'Moquillo (Distemper)');

-- ============================== ANALITOS ====================================
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD) VALUES (1,  'HCT', 'Hematocrito', '%', 'Microhematocrito');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD) VALUES (2,  'HGB', 'Hemoglobina', 'g/dL', 'Cianometahemoglobina');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD) VALUES (3,  'RBC', 'Eritrocitos', 'M/µL', 'Citometría de flujo');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD) VALUES (4,  'WBC', 'Leucocitos', 'x10³/µL', 'Citometría de flujo');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD) VALUES (5,  'PLT', 'Plaquetas', 'x10³/µL', 'Citometría de flujo');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD) VALUES (6,  'ALT', 'Alanino aminotransferasa', 'U/L', 'Cinético UV');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD) VALUES (7,  'AST', 'Aspartato aminotransferasa', 'U/L', 'Cinético UV');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD) VALUES (8,  'CREA', 'Creatinina', 'mg/dL', 'Jaffé cinético');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD) VALUES (9,  'BUN', 'Urea nitrogenada', 'mg/dL', 'Ureasa UV');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD) VALUES (10, 'GLU', 'Glucosa', 'mg/dL', 'Hexoquinasa');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD) VALUES (11, 'TP',  'Proteínas totales', 'g/dL', 'Biuret');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD) VALUES (12, 'ALB', 'Albumina', 'g/dL', 'Verde de bromocresol');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD) VALUES (13, 'PHOS', 'Fósforo', 'mg/dL', 'Fosfomolibdato UV');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD) VALUES (14, 'CA',  'Calcio total', 'mg/dL', 'Arsenazo III');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD) VALUES (15, 'T4',  'Tiroxina total (T4)', 'µg/dL', 'ELISA');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD) VALUES (16, 'BILIT', 'Bilirrubina total', 'mg/dL', 'Diazo');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD) VALUES (17, 'AMYL', 'Amilasa', 'U/L', 'Enzimático');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD) VALUES (18, 'LIP',  'Lipasa', 'U/L', 'Turbidimétrico');

-- ================== VALORES DE REFERENCIA (especie+edad+sexo) ===============
-- Convención de edades en MESES. SEX = NULL significa "ambos sexos".
-- Cachorro/cría (< 12 meses), adulto (12 a 200 años-mes), geronte (> 144).

-- ---- CANINO ----
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE, NOTES) VALUES
(1,   1, 1, NULL, 0,   11,  37, 55, 'Hematocrito cachorro');
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(2,   1, 1, NULL, 12,  2400, 37, 55);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(3,   2, 1, NULL, 12,  2400, 12, 18);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(4,   3, 1, NULL, 12,  2400, 5.5, 8.5);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(5,   4, 1, NULL, 12,  2400, 6.0, 17.0);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(6,   5, 1, NULL, 12,  2400, 200, 500);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(7,   6, 1, NULL, 12,  2400, 10, 100);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(8,   7, 1, NULL, 12,  2400, 10, 50);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(9,   8, 1, NULL, 12,  2400, 0.5, 1.5);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(10,  9, 1, NULL, 12,  2400, 10, 30);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(11, 10, 1, NULL, 12,  2400, 70, 120);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(12, 10, 1, NULL, 0,   11,  60, 120);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(13, 11, 1, NULL, 12,  2400, 5.5, 7.5);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(14, 12, 1, NULL, 12,  2400, 2.5, 4.0);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(15, 13, 1, NULL, 0,   11,  4.5, 8.5);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(16, 13, 1, NULL, 12,  2400, 2.5, 5.5);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(17, 14, 1, NULL, 12,  2400, 8.8, 11.5);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(18, 15, 1, NULL, 12,  2400, 1.0, 4.0);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(19, 16, 1, NULL, 12,  2400, 0.0, 0.4);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(20, 17, 1, NULL, 12,  2400, 300, 1100);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(21, 18, 1, NULL, 12,  2400, 0, 500);

-- ---- FELINO ----
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(22,  1, 2, NULL, 12, 2400, 30, 45);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(23,  2, 2, NULL, 12, 2400, 9, 15);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(24,  3, 2, NULL, 12, 2400, 5.0, 10.0);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(25,  4, 2, NULL, 12, 2400, 5.0, 19.5);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(26,  5, 2, NULL, 12, 2400, 300, 800);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(27,  6, 2, NULL, 12, 2400, 10, 100);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(28,  7, 2, NULL, 12, 2400, 10, 50);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(29,  8, 2, NULL, 12, 2400, 0.8, 2.4);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(30,  9, 2, NULL, 12, 2400, 15, 34);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(31, 10, 2, NULL, 12, 2400, 70, 150);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(32, 11, 2, NULL, 12, 2400, 5.5, 7.8);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(33, 12, 2, NULL, 12, 2400, 2.4, 3.8);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(34, 13, 2, NULL, 12, 2400, 2.5, 5.5);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(35, 14, 2, NULL, 12, 2400, 8.5, 11.0);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(36, 15, 2, NULL, 12, 2400, 0.8, 4.7);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(37, 16, 2, NULL, 12, 2400, 0.0, 0.3);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(38, 17, 2, NULL, 12, 2400, 400, 1300);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(39, 18, 2, NULL, 12, 2400, 0, 400);

-- ---- EQUINO (demostración multiespecie) ----
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(40,  1, 3, NULL, 12, 2400, 32, 53);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(41, 10, 3, NULL, 12, 2400, 70, 130);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(42,  8, 3, NULL, 12, 2400, 0.8, 1.8);

-- ---- BOVINO (demostración multiespecie) ----
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(43,  1, 4, NULL, 12, 2400, 24, 46);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(44, 10, 4, NULL, 12, 2400, 40, 90);
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE) VALUES
(45,  8, 4, NULL, 12, 2400, 0.8, 1.7);

-- ---- Ejemplo de rango específico por SEXO (T4 canino: hembra vs macho) ----
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE, NOTES) VALUES
(46, 15, 1, 'M', 12, 2400, 1.0, 3.6, 'T4 macho adulto');
INSERT INTO REFERENCE_RANGES (ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE, NOTES) VALUES
(47, 15, 1, 'F', 12, 2400, 1.0, 4.2, 'T4 hembra adulta');

-- ========================== CONFIGURACIÓN ===================================
INSERT INTO CLINIC_SETTINGS (KEY_NAME, VALUE_TEXT, DESCRIPTION) VALUES
('clinic.name', 'Mi Clínica Veterinaria', 'Nombre comercial de la clínica');
INSERT INTO CLINIC_SETTINGS (KEY_NAME, VALUE_TEXT, DESCRIPTION) VALUES
('clinic.nit', '900000000-0', 'NIT de la clínica');
INSERT INTO CLINIC_SETTINGS (KEY_NAME, VALUE_TEXT, DESCRIPTION) VALUES
('clinic.address', '', 'Dirección de la clínica');
INSERT INTO CLINIC_SETTINGS (KEY_NAME, VALUE_TEXT, DESCRIPTION) VALUES
('clinic.phone', '', 'Teléfono de la clínica');
INSERT INTO CLINIC_SETTINGS (KEY_NAME, VALUE_TEXT, DESCRIPTION) VALUES
('clinic.city', 'Bogotá D.C.', 'Ciudad de la clínica');
INSERT INTO CLINIC_SETTINGS (KEY_NAME, VALUE_TEXT, DESCRIPTION) VALUES
('clinic.logo_path', '', 'Ruta del logo (PNG) para reportes PDF');
INSERT INTO CLINIC_SETTINGS (KEY_NAME, VALUE_TEXT, DESCRIPTION) VALUES
('invoice.tax_rate', '19.00', 'IVA por defecto (%)');
INSERT INTO CLINIC_SETTINGS (KEY_NAME, VALUE_TEXT, DESCRIPTION) VALUES
('invoice.currency', 'COP', 'Moneda de facturación');
INSERT INTO CLINIC_SETTINGS (KEY_NAME, VALUE_TEXT, DESCRIPTION) VALUES
('report.signature_mode', 'GRAPHIC', 'Firma en PDF: GRAPHIC (imagen) o DIGITAL (PKCS#12)');
INSERT INTO CLINIC_SETTINGS (KEY_NAME, VALUE_TEXT, DESCRIPTION) VALUES
('report.vet_name', '', 'Nombre del médico veterinario firmante');
INSERT INTO CLINIC_SETTINGS (KEY_NAME, VALUE_TEXT, DESCRIPTION) VALUES
('report.vet_license', '', 'Nº de tarjeta profesional MVZ (Colombia)');

-- ========================== USUARIO ADMIN ===================================
-- El hash se asignará en el módulo de autenticación (bcrypt/argon2).
INSERT INTO USERS (ID, USERNAME, FULL_NAME, ROLE, PASSWORD_HASH, MUST_CHANGE_PASSWORD, ACTIVE)
VALUES (1, 'admin', 'Administrador', 'ADMIN', NULL, TRUE, TRUE);
