CREATE TABLE SECONDARY_LOGOS (
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) CHARACTER SET UTF8 NOT NULL,
    LOGO_PATH VARCHAR(300) CHARACTER SET UTF8 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE GENERATOR GEN_SECONDARY_LOGOS_SEQ;

SET TERM ^ ;
CREATE TRIGGER TR_SECONDARY_LOGOS_BI FOR SECONDARY_LOGOS ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_SECONDARY_LOGOS_SEQ, 1);
END^
SET TERM ; ^
