-- ============================================================================
-- ISALAB · Migración 0014 — Control de calidad interno (QC)
-- Materiales de control por equipo, valores objetivo (media/desviación) por
-- analito y corridas de control evaluadas con reglas multirregla de Westgard
-- (1_2s, 1_3s, 2_2s, R_4s, 4_1s, 10x). La evaluación se hace en Rust
-- (función pura testeable); aquí se persisten los resultados y violaciones.
-- ============================================================================

CREATE TABLE QC_CONTROL_MATERIALS (
    ID          D_PK NOT NULL PRIMARY KEY,
    NAME        D_NAME NOT NULL,
    ANALYZER_ID D_PK NOT NULL REFERENCES ANALYZERS (ID) ON DELETE CASCADE,
    LOT         VARCHAR(40) CHARACTER SET UTF8,
    EXPIRES_AT  DATE,
    IS_ACTIVE   BOOLEAN DEFAULT TRUE NOT NULL,
    NOTES       D_NOTES,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE GENERATOR GEN_QC_CONTROL_MATERIALS_ID;

CREATE TABLE QC_TARGETS (
    ID                  D_PK NOT NULL PRIMARY KEY,
    CONTROL_MATERIAL_ID D_PK NOT NULL REFERENCES QC_CONTROL_MATERIALS (ID) ON DELETE CASCADE,
    ANALYTE_ID          D_PK NOT NULL REFERENCES ANALYTES (ID) ON DELETE CASCADE,
    MEAN                DOUBLE PRECISION NOT NULL,
    SD                  DOUBLE PRECISION NOT NULL CHECK (SD > 0),
    UNIQUE (CONTROL_MATERIAL_ID, ANALYTE_ID)
);
CREATE GENERATOR GEN_QC_TARGETS_ID;

CREATE TABLE QC_RUNS (
    ID                  D_PK NOT NULL PRIMARY KEY,
    CONTROL_MATERIAL_ID D_PK NOT NULL REFERENCES QC_CONTROL_MATERIALS (ID) ON DELETE CASCADE,
    ANALYZER_ID         D_PK NOT NULL REFERENCES ANALYZERS (ID),
    RUN_DATE            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STATUS              D_STATUS NOT NULL CHECK (STATUS IN ('ACEPTADO', 'RECHAZADO')),
    NOTES               D_NOTES,
    CREATED_BY          D_PK REFERENCES USERS (ID) ON DELETE SET NULL,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE GENERATOR GEN_QC_RUNS_ID;

CREATE TABLE QC_RUN_MEASUREMENTS (
    ID         D_PK NOT NULL PRIMARY KEY,
    QC_RUN_ID  D_PK NOT NULL REFERENCES QC_RUNS (ID) ON DELETE CASCADE,
    ANALYTE_ID  D_PK NOT NULL REFERENCES ANALYTES (ID),
    RESULT_VALUE DOUBLE PRECISION NOT NULL,
    Z_SCORE      DOUBLE PRECISION,
    VIOLATION    VARCHAR(120) CHARACTER SET UTF8,
    UNIQUE (QC_RUN_ID, ANALYTE_ID)
);
CREATE GENERATOR GEN_QC_RUN_MEASUREMENTS_ID;