-- ============================================================================
-- ISALAB · Migración 0015 — Valores críticos (alertas clínicas)
-- La tabla REFERENCE_RANGES ya tiene CRITICAL_MIN/CRITICAL_MAX desde 0001,
-- pero SP_VALIDATE_ANALYTICAL_RESULT los ignoraba. Se recrea el SP para que
-- devuelva CRITICO_BAJO / CRITICO_ALTO cuando el valor cruza el umbral
-- crítico, y se amplía el CHECK de LAB_RESULTS.STATUS.
-- ============================================================================

-- ============== AMPLIAR EL CHECK DE LAB_RESULTS.STATUS ======================
SET TERM ^ ;

EXECUTE BLOCK AS
    DECLARE VARIABLE CN VARCHAR(63);
BEGIN
    SELECT FIRST 1 rc.RDB$CONSTRAINT_NAME
    FROM RDB$RELATION_CONSTRAINTS rc
    WHERE rc.RDB$RELATION_NAME = 'LAB_RESULTS'
      AND rc.RDB$CONSTRAINT_TYPE = 'CHECK'
    INTO :CN;
    IF (:CN IS NOT NULL) THEN
        EXECUTE STATEMENT 'ALTER TABLE LAB_RESULTS DROP CONSTRAINT ' || :CN;
END^

SET TERM ; ^

ALTER TABLE LAB_RESULTS ADD CONSTRAINT CK_LAB_RESULTS_STATUS
    CHECK (STATUS IN ('BAJO', 'NORMAL', 'ALTO', 'SIN_RANGO', 'CRITICO_BAJO', 'CRITICO_ALTO'));

-- ========== SP CON EVALUACIÓN DE VALORES CRÍTICOS ===========================
SET TERM ^ ;

DROP PROCEDURE SP_VALIDATE_ANALYTICAL_RESULT^

CREATE PROCEDURE SP_VALIDATE_ANALYTICAL_RESULT (
    P_SAMPLE_ID   INTEGER,
    P_ANALYTE_ID  INTEGER,
    P_VALUE       DOUBLE PRECISION
) RETURNS (
    RR_ID   INTEGER,
    STATUS  VARCHAR(12)
) AS
DECLARE VARIABLE V_SPECIES_ID  INTEGER;
DECLARE VARIABLE V_SEX         CHAR(1);
DECLARE VARIABLE V_AGE_MONTHS  INTEGER;
DECLARE VARIABLE V_ANALYZER_ID INTEGER;
DECLARE VARIABLE V_MIN         DOUBLE PRECISION;
DECLARE VARIABLE V_MAX         DOUBLE PRECISION;
DECLARE VARIABLE V_CRIT_MIN    DOUBLE PRECISION;
DECLARE VARIABLE V_CRIT_MAX    DOUBLE PRECISION;
BEGIN
    SELECT FIRST 1 pa.SPECIES_ID, pa.SEX,
           COALESCE(CAST(DATEDIFF(MONTH, pa.BIRTH_DATE, CURRENT_TIMESTAMP) AS INTEGER), 0),
           sa.ANALYZER_ID
    FROM SAMPLES sa
    JOIN PATIENTS pa ON pa.ID = sa.PATIENT_ID
    WHERE sa.ID = :P_SAMPLE_ID
    INTO :V_SPECIES_ID, :V_SEX, :V_AGE_MONTHS, :V_ANALYZER_ID;

    IF (:V_SPECIES_ID IS NULL) THEN
    BEGIN
        RR_ID  = NULL;
        STATUS = 'SIN_RANGO';
        SUSPEND;
        EXIT;
    END

    SELECT RR_ID, MIN_VALUE, MAX_VALUE, CRITICAL_MIN, CRITICAL_MAX
    FROM SP_FIND_REFERENCE_RANGE(:P_ANALYTE_ID, :V_SPECIES_ID, :V_SEX, :V_AGE_MONTHS, :V_ANALYZER_ID)
    INTO :RR_ID, :V_MIN, :V_MAX, :V_CRIT_MIN, :V_CRIT_MAX;

    IF (:RR_ID IS NULL) THEN
    BEGIN
        STATUS = 'SIN_RANGO';
        SUSPEND;
        EXIT;
    END

    -- Precedencia: crítico > fuera de rango > normal. Los umbrales críticos
    -- deben configurarse FUERA del rango de referencia (p. ej. K+ normal
    -- 3.5–5.5, crítico < 2.8 o > 7.5).
    IF (:V_CRIT_MAX IS NOT NULL AND :P_VALUE > :V_CRIT_MAX) THEN
        STATUS = 'CRITICO_ALTO';
    ELSE IF (:V_CRIT_MIN IS NOT NULL AND :P_VALUE < :V_CRIT_MIN) THEN
        STATUS = 'CRITICO_BAJO';
    ELSE IF (:P_VALUE < :V_MIN) THEN
        STATUS = 'BAJO';
    ELSE IF (:P_VALUE > :V_MAX) THEN
        STATUS = 'ALTO';
    ELSE
        STATUS = 'NORMAL';

    SUSPEND;
END^

SET TERM ; ^