-- ============================================================================
-- ISALAB · Migración 0020 — Analitos y Paneles de Urianálisis y Bioquímica
-- Agrega analitos estándar de orina (físico-químico y sedimento), rangos de
-- referencia para caninos, felinos y equinos, y paneles predeterminados para
-- Orina (sample_type_id = 4) y Suero (sample_type_id = 2).
-- ============================================================================

-- ==================== TRIGGERS BI PARA PANELES ==============================
SET TERM ^ ;

CREATE OR ALTER TRIGGER BI_PANELS FOR PANELS BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_PANELS_ID, 1);
END^

CREATE OR ALTER TRIGGER BI_PANEL_ANALYTES FOR PANEL_ANALYTES BEFORE INSERT AS
BEGIN
    IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_PANEL_ANALYTES_ID, 1);
END^

SET TERM ; ^

-- ==================== ANALITOS DE URIANÁLISIS ===============================
-- Avanza el generador de analitos por encima de los IDs sembrados por 0002
-- (IDs 1-18) **solo si** todavía está por debajo. En una DB nueva el generador
-- está en 0 y el primer GEN_ID(...) devolvería 1, colisionando con la PK de
-- 'HCT'. Un SET GENERATOR incondicional regresaría el generador en clínicas
-- que ya crearon analitos propios (mismo patrón idempotente que la 0010).
SET TERM ^ ;

EXECUTE BLOCK AS
    DECLARE VARIABLE CURR INTEGER;
BEGIN
    CURR = GEN_ID(GEN_ANALYTES_ID, 0);
    IF (CURR < 18) THEN
        CURR = GEN_ID(GEN_ANALYTES_ID, 18 - CURR);
END^

SET TERM ; ^

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'DENS', 'Densidad urinaria (USG)', 'g/mL', 'Refractometría', 'Gravedad específica de la orina');

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'PH_UR', 'pH urinario', 'pH', 'Tira reactiva', 'Acidez/alcalinidad de la orina');

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'PROT_UR', 'Proteínas en orina', 'mg/dL', 'Tira reactiva', 'Concentración de proteínas');

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'GLU_UR', 'Glucosa en orina', 'mg/dL', 'Tira reactiva', 'Glucosuria');

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'CET_UR', 'Cetonas en orina', 'mg/dL', 'Tira reactiva', 'Cetonuria');

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'BIL_UR', 'Bilirrubina urinaria', 'mg/dL', 'Tira reactiva', 'Bilirrubinuria');

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'SANG_UR', 'Sangre / Hemoglobina', 'Ery/µL', 'Tira reactiva', 'Hematuria / hemoglobinuria');

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'URO_UR', 'Urobilinógeno', 'mg/dL', 'Tira reactiva', 'Urobilinogenuria');

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'NIT_UR', 'Nitritos', 'mg/dL', 'Tira reactiva', 'Presencia de bacterias reductoras de nitrato');

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'LEU_UR', 'Leucocitos en orina', 'Leu/µL', 'Tira reactiva', 'Leucocituria');

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'UPC', 'Relación Proteína/Creatinina (UPC)', 'ratio', 'Química cuantitativa', 'Cociente proteína:creatinina urinaria');

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'ERY_CAMP', 'Eritrocitos en sedimento', '/cpo', 'Microscopía 40x', 'Hematíes por campo');

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'LEU_CAMP', 'Leucocitos en sedimento', '/cpo', 'Microscopía 40x', 'Leucocitos por campo');

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'CEL_EPIT', 'Células epiteliales', '/cpo', 'Microscopía 40x', 'Células epiteliales descamativas');

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'CILIND', 'Cilindros', '/cpo', 'Microscopía 40x', 'Cilindros granulosos, hialinos o cerosos');

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'CRIST', 'Cristales', '/cpo', 'Microscopía 40x', 'Cristaluria (estruvita, oxalato, uratos)');

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'BACT', 'Bacterias', '/cpo', 'Microscopía 40x', 'Bacteriuria');

-- ==================== RANGOS DE REFERENCIA URIANÁLISIS =======================
-- Canino (SPECIES_ID = 1)
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 1.015, 1.045 FROM ANALYTES a WHERE a.CODE = 'DENS';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 5.5, 7.5 FROM ANALYTES a WHERE a.CODE = 'PH_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 30 FROM ANALYTES a WHERE a.CODE = 'PROT_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 0 FROM ANALYTES a WHERE a.CODE = 'GLU_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 0 FROM ANALYTES a WHERE a.CODE = 'CET_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 0.5 FROM ANALYTES a WHERE a.CODE = 'BIL_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 5 FROM ANALYTES a WHERE a.CODE = 'SANG_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0.1, 1.0 FROM ANALYTES a WHERE a.CODE = 'URO_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 0 FROM ANALYTES a WHERE a.CODE = 'NIT_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 10 FROM ANALYTES a WHERE a.CODE = 'LEU_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 0.5 FROM ANALYTES a WHERE a.CODE = 'UPC';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 5 FROM ANALYTES a WHERE a.CODE = 'ERY_CAMP';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 5 FROM ANALYTES a WHERE a.CODE = 'LEU_CAMP';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 3 FROM ANALYTES a WHERE a.CODE = 'CEL_EPIT';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 1 FROM ANALYTES a WHERE a.CODE = 'CILIND';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 0 FROM ANALYTES a WHERE a.CODE = 'CRIST';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 0 FROM ANALYTES a WHERE a.CODE = 'BACT';

-- Felino (SPECIES_ID = 2)
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 1.020, 1.060 FROM ANALYTES a WHERE a.CODE = 'DENS';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 6.0, 7.5 FROM ANALYTES a WHERE a.CODE = 'PH_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 30 FROM ANALYTES a WHERE a.CODE = 'PROT_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 0 FROM ANALYTES a WHERE a.CODE = 'GLU_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 0 FROM ANALYTES a WHERE a.CODE = 'CET_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 0 FROM ANALYTES a WHERE a.CODE = 'BIL_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 5 FROM ANALYTES a WHERE a.CODE = 'SANG_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0.1, 1.0 FROM ANALYTES a WHERE a.CODE = 'URO_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 0 FROM ANALYTES a WHERE a.CODE = 'NIT_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 10 FROM ANALYTES a WHERE a.CODE = 'LEU_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 0.4 FROM ANALYTES a WHERE a.CODE = 'UPC';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 5 FROM ANALYTES a WHERE a.CODE = 'ERY_CAMP';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 5 FROM ANALYTES a WHERE a.CODE = 'LEU_CAMP';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 3 FROM ANALYTES a WHERE a.CODE = 'CEL_EPIT';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 1 FROM ANALYTES a WHERE a.CODE = 'CILIND';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 0 FROM ANALYTES a WHERE a.CODE = 'CRIST';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 0 FROM ANALYTES a WHERE a.CODE = 'BACT';

-- Equino (SPECIES_ID = 3)
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 1.020, 1.050 FROM ANALYTES a WHERE a.CODE = 'DENS';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 7.0, 8.5 FROM ANALYTES a WHERE a.CODE = 'PH_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0, 30 FROM ANALYTES a WHERE a.CODE = 'PROT_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0, 0 FROM ANALYTES a WHERE a.CODE = 'GLU_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0, 0 FROM ANALYTES a WHERE a.CODE = 'CET_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0, 0 FROM ANALYTES a WHERE a.CODE = 'BIL_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0, 5 FROM ANALYTES a WHERE a.CODE = 'SANG_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0.1, 1.0 FROM ANALYTES a WHERE a.CODE = 'URO_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0, 10 FROM ANALYTES a WHERE a.CODE = 'LEU_UR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0, 5 FROM ANALYTES a WHERE a.CODE = 'ERY_CAMP';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0, 5 FROM ANALYTES a WHERE a.CODE = 'LEU_CAMP';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0, 3 FROM ANALYTES a WHERE a.CODE = 'CEL_EPIT';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0, 1 FROM ANALYTES a WHERE a.CODE = 'CILIND';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0, 5 FROM ANALYTES a WHERE a.CODE = 'CRIST';

-- ==================== PANELES PREDETERMINADOS ===============================

-- 1. Panel "Urianálisis completo" (SAMPLE_TYPE_ID = 4: Orina)
INSERT INTO PANELS (ID, NAME, SAMPLE_TYPE_ID, SORT_ORDER, IS_ACTIVE, NOTES)
VALUES (2, 'Urianálisis completo', 4, 10, TRUE,
        'Examen físico-químico y sedimento urinario completo');

INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 2, a.ID, 10 FROM ANALYTES a WHERE a.CODE = 'DENS';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 2, a.ID, 20 FROM ANALYTES a WHERE a.CODE = 'PH_UR';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 2, a.ID, 30 FROM ANALYTES a WHERE a.CODE = 'PROT_UR';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 2, a.ID, 40 FROM ANALYTES a WHERE a.CODE = 'GLU_UR';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 2, a.ID, 50 FROM ANALYTES a WHERE a.CODE = 'CET_UR';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 2, a.ID, 60 FROM ANALYTES a WHERE a.CODE = 'BIL_UR';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 2, a.ID, 70 FROM ANALYTES a WHERE a.CODE = 'SANG_UR';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 2, a.ID, 80 FROM ANALYTES a WHERE a.CODE = 'URO_UR';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 2, a.ID, 90 FROM ANALYTES a WHERE a.CODE = 'NIT_UR';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 2, a.ID, 100 FROM ANALYTES a WHERE a.CODE = 'LEU_UR';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 2, a.ID, 110 FROM ANALYTES a WHERE a.CODE = 'UPC';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 2, a.ID, 120 FROM ANALYTES a WHERE a.CODE = 'ERY_CAMP';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 2, a.ID, 130 FROM ANALYTES a WHERE a.CODE = 'LEU_CAMP';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 2, a.ID, 140 FROM ANALYTES a WHERE a.CODE = 'CEL_EPIT';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 2, a.ID, 150 FROM ANALYTES a WHERE a.CODE = 'CILIND';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 2, a.ID, 160 FROM ANALYTES a WHERE a.CODE = 'CRIST';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 2, a.ID, 170 FROM ANALYTES a WHERE a.CODE = 'BACT';

-- 2. Panel "Perfil bioquímico general" (SAMPLE_TYPE_ID = 2: Suero)
INSERT INTO PANELS (ID, NAME, SAMPLE_TYPE_ID, SORT_ORDER, IS_ACTIVE, NOTES)
VALUES (3, 'Perfil bioquímico general', 2, 20, TRUE,
        'Panel general de química sanguínea: renal, hepático y glucídico');

INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 3, a.ID, 10 FROM ANALYTES a WHERE a.CODE = 'ALT';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 3, a.ID, 20 FROM ANALYTES a WHERE a.CODE = 'AST';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 3, a.ID, 30 FROM ANALYTES a WHERE a.CODE = 'CREA';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 3, a.ID, 40 FROM ANALYTES a WHERE a.CODE = 'BUN';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 3, a.ID, 50 FROM ANALYTES a WHERE a.CODE = 'GLU';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 3, a.ID, 60 FROM ANALYTES a WHERE a.CODE = 'TP';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 3, a.ID, 70 FROM ANALYTES a WHERE a.CODE = 'ALB';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 3, a.ID, 80 FROM ANALYTES a WHERE a.CODE = 'PHOS';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 3, a.ID, 90 FROM ANALYTES a WHERE a.CODE = 'CA';

-- 3. Panel "Perfil renal" (SAMPLE_TYPE_ID = 2: Suero)
INSERT INTO PANELS (ID, NAME, SAMPLE_TYPE_ID, SORT_ORDER, IS_ACTIVE, NOTES)
VALUES (4, 'Perfil renal', 2, 30, TRUE,
        'Evaluación de función renal: creatinina, urea, fósforo, calcio y albúmina');

INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 4, a.ID, 10 FROM ANALYTES a WHERE a.CODE = 'CREA';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 4, a.ID, 20 FROM ANALYTES a WHERE a.CODE = 'BUN';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 4, a.ID, 30 FROM ANALYTES a WHERE a.CODE = 'PHOS';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 4, a.ID, 40 FROM ANALYTES a WHERE a.CODE = 'CA';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 4, a.ID, 50 FROM ANALYTES a WHERE a.CODE = 'ALB';

-- 4. Panel "Perfil hepático" (SAMPLE_TYPE_ID = 2: Suero)
INSERT INTO PANELS (ID, NAME, SAMPLE_TYPE_ID, SORT_ORDER, IS_ACTIVE, NOTES)
VALUES (5, 'Perfil hepático', 2, 40, TRUE,
        'Evaluación hepatobiliar: transaminasas, bilirrubina y proteínas');

INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 5, a.ID, 10 FROM ANALYTES a WHERE a.CODE = 'ALT';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 5, a.ID, 20 FROM ANALYTES a WHERE a.CODE = 'AST';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 5, a.ID, 30 FROM ANALYTES a WHERE a.CODE = 'BILIT';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 5, a.ID, 40 FROM ANALYTES a WHERE a.CODE = 'TP';
INSERT INTO PANEL_ANALYTES (ID, PANEL_ID, ANALYTE_ID, SEQ)
SELECT GEN_ID(GEN_PANEL_ANALYTES_ID, 1), 5, a.ID, 50 FROM ANALYTES a WHERE a.CODE = 'ALB';

-- Actualizar generador de paneles
SET TERM ^ ;
EXECUTE BLOCK AS
    DECLARE VARIABLE M INTEGER;
BEGIN
    SELECT COALESCE(MAX(ID), 5) FROM PANELS INTO :M;
    EXECUTE STATEMENT 'SET GENERATOR GEN_PANELS_ID TO ' || :M;
    SELECT COALESCE(MAX(ID), 100) FROM PANEL_ANALYTES INTO :M;
    EXECUTE STATEMENT 'SET GENERATOR GEN_PANEL_ANALYTES_ID TO ' || :M;
END^
SET TERM ; ^
