-- ============================================================================
-- 0021 — Catálogo de valores de referencia veterinarios
-- ============================================================================
-- Analitos y rangos de referencia destilados de
-- `Valores_Referencia_Veterinarios.md` (UPEI, Cornell/eClinPath, VetBlood.io,
-- Merck Veterinary Manual, LABOKLIN, IRIS; compilación sep 2026).
--
-- Unidades CONVENCIONALES (US) para coincidir con el catálogo existente
-- (HGB en g/dL, CREA en mg/dL, …). El intervalo del laboratorio propio siempre
-- tiene prioridad: los rangos se pueden ajustar desde la UI
-- (Ajustes → Equipos y rangos) y los analitos ausentes se pueden crear allí.
--
-- ANALYZER_ID = 1 → perfil GENERAL (rangos estándar por especie).
-- SEX NULL = ambos sexos; edades 0–2400 meses (adulto).
-- Los valores críticos (CRITICAL_MIN/MAX) no vienen en la fuente: quedan NULL.

-- ========================= HEMATOLOGÍA (CBC) ================================

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'MCV', 'Volumen corpuscular medio (MCV)', 'fL', 'Hematología automatizada', 'Volumen medio del eritrocito');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'MCH', 'Hemoglobina corpuscular media (MCH)', 'pg', 'Hematología automatizada', 'Hemoglobina media por eritrocito');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'MCHC', 'Concentración media de Hb corpuscular (MCHC)', 'g/dL', 'Hematología automatizada', 'Concentración media de hemoglobina');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'NEUT', 'Neutrófilos segmentados', 'x10³/µL', 'Hematología automatizada', 'Serie granulocítica neutrófila');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'LYM', 'Linfocitos', 'x10³/µL', 'Hematología automatizada', 'Serie linfocitaria');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'MONO', 'Monocitos', 'x10³/µL', 'Hematología automatizada', 'Serie monocítica');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'EOS', 'Eosinófilos', 'x10³/µL', 'Hematología automatizada', 'Serie eosinófila');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'BASO', 'Basófilos', 'x10³/µL', 'Hematología automatizada', 'Serie basófila');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'RETIC', 'Reticulocitos', '%', 'Azul cresil brillante', 'Respuesta regenerativa medular');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'MPV', 'Volumen plaquetario medio (MPV)', 'fL', 'Hematología automatizada', 'Tamaño medio de plaquetas');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'RDW', 'Amplitud de distribución eritrocitaria (RDW)', '%', 'Hematología automatizada', 'Anisocitosis');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'FIB', 'Fibrinógeno', 'mg/dL', 'Método de heat precipitation', 'Proteína de fase aguda / coagulación');

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 64, 76 FROM ANALYTES a WHERE a.CODE = 'MCV';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 40, 52 FROM ANALYTES a WHERE a.CODE = 'MCV';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 43, 55 FROM ANALYTES a WHERE a.CODE = 'MCV';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 21, 26 FROM ANALYTES a WHERE a.CODE = 'MCH';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 13, 17 FROM ANALYTES a WHERE a.CODE = 'MCH';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 15, 20 FROM ANALYTES a WHERE a.CODE = 'MCH';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 33, 36 FROM ANALYTES a WHERE a.CODE = 'MCHC';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 32, 35 FROM ANALYTES a WHERE a.CODE = 'MCHC';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 34, 37 FROM ANALYTES a WHERE a.CODE = 'MCHC';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 2.7, 9.4 FROM ANALYTES a WHERE a.CODE = 'NEUT';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 2.3, 11.6 FROM ANALYTES a WHERE a.CODE = 'NEUT';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 2.7, 6.6 FROM ANALYTES a WHERE a.CODE = 'NEUT';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0.9, 4.7 FROM ANALYTES a WHERE a.CODE = 'LYM';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0.9, 6.0 FROM ANALYTES a WHERE a.CODE = 'LYM';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 1.2, 4.9 FROM ANALYTES a WHERE a.CODE = 'LYM';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0.1, 1.3 FROM ANALYTES a WHERE a.CODE = 'MONO';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0.0, 0.7 FROM ANALYTES a WHERE a.CODE = 'MONO';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0.0, 0.6 FROM ANALYTES a WHERE a.CODE = 'MONO';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0.1, 2.1 FROM ANALYTES a WHERE a.CODE = 'EOS';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0.1, 1.8 FROM ANALYTES a WHERE a.CODE = 'EOS';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0.0, 1.2 FROM ANALYTES a WHERE a.CODE = 'EOS';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0.0, 0.1 FROM ANALYTES a WHERE a.CODE = 'BASO';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0.0, 0.2 FROM ANALYTES a WHERE a.CODE = 'BASO';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0.0, 0.2 FROM ANALYTES a WHERE a.CODE = 'BASO';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0.2, 1.5 FROM ANALYTES a WHERE a.CODE = 'RETIC';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0.1, 0.7 FROM ANALYTES a WHERE a.CODE = 'RETIC';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 6.1, 10.1 FROM ANALYTES a WHERE a.CODE = 'MPV';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 12, 18 FROM ANALYTES a WHERE a.CODE = 'MPV';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 4.0, 6.0 FROM ANALYTES a WHERE a.CODE = 'MPV';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 10.6, 14.3 FROM ANALYTES a WHERE a.CODE = 'RDW';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 13.2, 17.5 FROM ANALYTES a WHERE a.CODE = 'RDW';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 16.3, 19.3 FROM ANALYTES a WHERE a.CODE = 'RDW';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE, NOTES)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 150, 300, 'Equivalente a 1.5–3.0 g/L' FROM ANALYTES a WHERE a.CODE = 'FIB';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE, NOTES)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 150, 300, 'Equivalente a 1.5–3.0 g/L' FROM ANALYTES a WHERE a.CODE = 'FIB';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE, NOTES)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0, 500, 'Equino: < 5.0 g/L' FROM ANALYTES a WHERE a.CODE = 'FIB';

-- ========================= BIOQUÍMICA SANGUÍNEA =============================

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'NA', 'Sodio', 'mEq/L', 'Electrodo selectivo (ISE)', 'Electrolito sérico');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'K', 'Potasio', 'mEq/L', 'Electrodo selectivo (ISE)', 'Electrolito sérico');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'CL', 'Cloruro', 'mEq/L', 'Electrodo selectivo (ISE)', 'Electrolito sérico');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'CHOL', 'Colesterol', 'mg/dL', 'Enzimático CHOD-PAP', 'Perfil lipídico');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'TRIG', 'Triglicéridos', 'mg/dL', 'Enzimático GPO-PAP', 'Perfil lipídico');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'SDMA', 'SDMA (dimetilarginina simétrica)', 'µg/dL', 'Inmunoensayo', 'Marcador temprano de función renal');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'LACT', 'Lactato', 'mmol/L', 'Enzimático (lactato oxidasa)', 'Perfusión tisular / hipoxia');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'MG', 'Magnesio', 'mg/dL', 'Colorimétrico (xilidol azul)', 'Electrolito sérico');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'UA', 'Ácido úrico', 'mg/dL', 'Uricasa', 'Metabolismo de purinas (dálmatas, aves)');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'TBA', 'Ácidos biliares', 'µmol/L', 'Enzimático circular', 'Función hepática (pre/postprandial)');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'GGT', 'Gamma glutamil transferasa (GGT)', 'U/L', 'Cinético IFCC', 'Enzima colestásica');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'GLDH', 'Deshidrogenasa glutámica (GLDH)', 'U/L', 'Cinético UV', 'Enzima hepática específica (equinos)');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'ALP', 'Fosfatasa alcalina (ALP)', 'U/L', 'Cinético IFCC', 'Enzima colestásica / ósea');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'GLOB', 'Globulinas', 'g/dL', 'Cálculo (PT − ALB)', 'Fracción globulínica');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'AGR', 'Relación albúmina/globulina (A/G)', 'ratio', 'Cálculo', 'Cociente albúmina:globulina');

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 143, 150 FROM ANALYTES a WHERE a.CODE = 'NA';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 149, 158 FROM ANALYTES a WHERE a.CODE = 'NA';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 134, 142 FROM ANALYTES a WHERE a.CODE = 'NA';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 4.1, 5.4 FROM ANALYTES a WHERE a.CODE = 'K';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 3.8, 5.5 FROM ANALYTES a WHERE a.CODE = 'K';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 2.4, 4.8 FROM ANALYTES a WHERE a.CODE = 'K';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 106, 114 FROM ANALYTES a WHERE a.CODE = 'CL';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 111, 124 FROM ANALYTES a WHERE a.CODE = 'CL';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 95, 104 FROM ANALYTES a WHERE a.CODE = 'CL';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 136, 392 FROM ANALYTES a WHERE a.CODE = 'CHOL';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 101, 323 FROM ANALYTES a WHERE a.CODE = 'CHOL';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 68, 133 FROM ANALYTES a WHERE a.CODE = 'CHOL';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 23, 102 FROM ANALYTES a WHERE a.CODE = 'TRIG';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 30, 106 FROM ANALYTES a WHERE a.CODE = 'TRIG';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 14, 65 FROM ANALYTES a WHERE a.CODE = 'TRIG';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 14 FROM ANALYTES a WHERE a.CODE = 'SDMA';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 14 FROM ANALYTES a WHERE a.CODE = 'SDMA';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE, NOTES)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 3.0, 'Canino: < 3.0 mmol/L' FROM ANALYTES a WHERE a.CODE = 'LACT';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE, NOTES)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 3.0, 'Felino: < 3.0 mmol/L' FROM ANALYTES a WHERE a.CODE = 'LACT';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0.5, 2.0 FROM ANALYTES a WHERE a.CODE = 'LACT';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0.1, 0.9 FROM ANALYTES a WHERE a.CODE = 'UA';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 1.6, 2.4 FROM ANALYTES a WHERE a.CODE = 'MG';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 1.7, 2.6 FROM ANALYTES a WHERE a.CODE = 'MG';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 1.4, 2.3 FROM ANALYTES a WHERE a.CODE = 'MG';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 6 FROM ANALYTES a WHERE a.CODE = 'TBA';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 3 FROM ANALYTES a WHERE a.CODE = 'TBA';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 2, 10 FROM ANALYTES a WHERE a.CODE = 'TBA';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 8 FROM ANALYTES a WHERE a.CODE = 'GGT';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 2 FROM ANALYTES a WHERE a.CODE = 'GGT';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 8, 33 FROM ANALYTES a WHERE a.CODE = 'GGT';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 1, 20 FROM ANALYTES a WHERE a.CODE = 'GLDH';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0, 12 FROM ANALYTES a WHERE a.CODE = 'GLDH';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 2, 10 FROM ANALYTES a WHERE a.CODE = 'GLDH';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 7, 115 FROM ANALYTES a WHERE a.CODE = 'ALP';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 11, 49 FROM ANALYTES a WHERE a.CODE = 'ALP';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 88, 261 FROM ANALYTES a WHERE a.CODE = 'ALP';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 1.9, 3.7 FROM ANALYTES a WHERE a.CODE = 'GLOB';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 2.9, 4.7 FROM ANALYTES a WHERE a.CODE = 'GLOB';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 2.3, 3.8 FROM ANALYTES a WHERE a.CODE = 'GLOB';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0.9, 1.9 FROM ANALYTES a WHERE a.CODE = 'AGR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0.8, 1.5 FROM ANALYTES a WHERE a.CODE = 'AGR';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0.8, 1.5 FROM ANALYTES a WHERE a.CODE = 'AGR';

-- ================ GASES SANGUÍNEOS Y EQUILIBRIO ÁCIDO-BASE ==================

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'PH_ART', 'pH arterial', 'pH', 'Gasometría', 'Equilibrio ácido-base');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'PCO2_VEN', 'pCO₂ venoso', 'mmHg', 'Gasometría', 'Presión parcial de CO₂');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'PO2_ART', 'pO₂ arterial', 'mmHg', 'Gasometría', 'Presión parcial de O₂');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'HCO3', 'Bicarbonato (HCO₃⁻)', 'mmol/L', 'Gasometría (calculado)', 'Componente metabólico');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'BE', 'Exceso de bases (BE)', 'mmol/L', 'Gasometría (calculado)', 'Exceso/déficit de bases');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'AG', 'Anion gap', 'mEq/L', 'Calculado (NA − CL − HCO3)', 'Brecha aniónica');

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 7.31, 7.42 FROM ANALYTES a WHERE a.CODE = 'PH_ART';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 7.24, 7.40 FROM ANALYTES a WHERE a.CODE = 'PH_ART';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 7.32, 7.44 FROM ANALYTES a WHERE a.CODE = 'PH_ART';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 34, 45 FROM ANALYTES a WHERE a.CODE = 'PCO2_VEN';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 25, 35 FROM ANALYTES a WHERE a.CODE = 'PCO2_VEN';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 38, 46 FROM ANALYTES a WHERE a.CODE = 'PCO2_VEN';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 80, 110 FROM ANALYTES a WHERE a.CODE = 'PO2_ART';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 80, 110 FROM ANALYTES a WHERE a.CODE = 'PO2_ART';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 85, 95 FROM ANALYTES a WHERE a.CODE = 'PO2_ART';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 20, 28 FROM ANALYTES a WHERE a.CODE = 'HCO3';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 20, 28 FROM ANALYTES a WHERE a.CODE = 'HCO3';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 25, 31 FROM ANALYTES a WHERE a.CODE = 'HCO3';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, -3, 3 FROM ANALYTES a WHERE a.CODE = 'BE';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, -3, 3 FROM ANALYTES a WHERE a.CODE = 'BE';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, -3, 3 FROM ANALYTES a WHERE a.CODE = 'BE';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 12, 25 FROM ANALYTES a WHERE a.CODE = 'AG';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 17, 31 FROM ANALYTES a WHERE a.CODE = 'AG';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 6, 21 FROM ANALYTES a WHERE a.CODE = 'AG';

-- ============================== COAGULACIÓN =================================

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'PT', 'Tiempo de protrombina (PT)', 's', 'Coagulometría', 'Vía extrínseca');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'APTT', 'Tiempo de tromboplastina parcial activado (TTPa)', 's', 'Coagulometría', 'Vía intrínseca');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'AT3', 'Antitrombina', '%', 'Cromogénico', 'Inhibidor de la coagulación');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'DDIM', 'Dímero D', 'ng/mL', 'Inmunoensayo', 'Producto de degradación de fibrina');

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 6.1, 8.0 FROM ANALYTES a WHERE a.CODE = 'PT';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 8.4, 14.7 FROM ANALYTES a WHERE a.CODE = 'PT';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 10.7, 12.0 FROM ANALYTES a WHERE a.CODE = 'PT';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 8.8, 14.8 FROM ANALYTES a WHERE a.CODE = 'APTT';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 10.8, 16.9 FROM ANALYTES a WHERE a.CODE = 'APTT';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 35.0, 46.1 FROM ANALYTES a WHERE a.CODE = 'APTT';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 65, 145 FROM ANALYTES a WHERE a.CODE = 'AT3';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 75, 100 FROM ANALYTES a WHERE a.CODE = 'AT3';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 85, 130 FROM ANALYTES a WHERE a.CODE = 'AT3';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 186 FROM ANALYTES a WHERE a.CODE = 'DDIM';

-- ============================= ENDOCRINOLOGÍA ===============================

INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'CORT', 'Cortisol basal', 'µg/dL', 'Inmunoensayo (CLIA/ELISA)', 'Eje hipotálamo-hipófisis-adrenal');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'CORT_STIM', 'Cortisol post-ACTH', 'µg/dL', 'Inmunoensayo (CLIA/ELISA)', 'Prueba de estimulación con ACTH');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'T3', 'Triyodotironina (T3)', 'nmol/L', 'Inmunoensayo', 'Hormona tiroidea');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'TSH', 'Hormona estimulante de tiroides (TSH)', 'ng/mL', 'Inmunoensayo', 'Eje hipófiso-tiroideo (canino)');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'INS', 'Insulina', 'µU/mL', 'Inmunoensayo', 'Metabolismo de la glucosa');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'FRUC', 'Fructosamina', 'µmol/L', 'Cinético colorimétrico', 'Glucemia media 1–2 semanas');
INSERT INTO ANALYTES (ID, CODE, NAME, UNIT, METHOD, DESCRIPTION) VALUES
(GEN_ID(GEN_ANALYTES_ID, 1), 'TESTO', 'Testosterona', 'ng/mL', 'Inmunoensayo', 'Machos intactos (temporada reproductiva en equinos)');

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE, NOTES)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0.5, 6.5, 'Equivalente a 14–180 nmol/L' FROM ANALYTES a WHERE a.CODE = 'CORT';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE, NOTES)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0.5, 4.0, 'Equivalente a 13–110 nmol/L' FROM ANALYTES a WHERE a.CODE = 'CORT';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE, NOTES)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 2.5, 6.5, 'Equivalente a 70–180 nmol/L' FROM ANALYTES a WHERE a.CODE = 'CORT';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE, NOTES)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 8.4, 20.7, 'Canino: 2 h post-ACTH (231–571 nmol/L)' FROM ANALYTES a WHERE a.CODE = 'CORT_STIM';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE, NOTES)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 5.9, 18.4, 'Felino: 1–2 h post-ACTH (163–507 nmol/L)' FROM ANALYTES a WHERE a.CODE = 'CORT_STIM';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0.6, 2.4 FROM ANALYTES a WHERE a.CODE = 'T3';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0.3, 1.7 FROM ANALYTES a WHERE a.CODE = 'T3';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0.9, 3.1 FROM ANALYTES a WHERE a.CODE = 'T3';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE, NOTES)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 0, 0.5, 'Canino: < 0.50 ng/mL' FROM ANALYTES a WHERE a.CODE = 'TSH';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 0.03, 0.30 FROM ANALYTES a WHERE a.CODE = 'TSH';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 8, 25 FROM ANALYTES a WHERE a.CODE = 'INS';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 10, 30 FROM ANALYTES a WHERE a.CODE = 'INS';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE, NOTES)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 0, 20, 'Equino: < 20 µU/mL' FROM ANALYTES a WHERE a.CODE = 'INS';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, NULL, 0, 2400, 274, 412 FROM ANALYTES a WHERE a.CODE = 'FRUC';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, NULL, 0, 2400, 219, 365 FROM ANALYTES a WHERE a.CODE = 'FRUC';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, NULL, 0, 2400, 195, 302 FROM ANALYTES a WHERE a.CODE = 'FRUC';

INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE, NOTES)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 1, 'M', 0, 2400, 1.0, 7.0, 'Macho intacto' FROM ANALYTES a WHERE a.CODE = 'TESTO';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE, NOTES)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 2, 'M', 0, 2400, 1.0, 6.0, 'Macho intacto' FROM ANALYTES a WHERE a.CODE = 'TESTO';
INSERT INTO REFERENCE_RANGES (ID, ANALYZER_ID, ANALYTE_ID, SPECIES_ID, SEX, AGE_MIN_MONTHS, AGE_MAX_MONTHS, MIN_VALUE, MAX_VALUE, NOTES)
SELECT GEN_ID(GEN_REFERENCE_RANGES_ID, 1), 1, a.ID, 3, 'M', 0, 2400, 1.0, 4.0, 'Macho intacto, temporada reproductiva' FROM ANALYTES a WHERE a.CODE = 'TESTO';
