import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";

export default tseslint.config(
  // Global ignores
  {
    ignores: [
      "dist/",
      "src-tauri/",
      "node_modules/",
      "scripts/",
      "ISALAB-TR-improvements/",
      "src/bindings.ts", // Auto-generated by specta
    ],
  },

  // Base rules
  js.configs.recommended,

  // TypeScript rules
  ...tseslint.configs.recommended,

  // React + Hooks rules for source files
  {
    files: ["src/**/*.{ts,tsx}"],
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    languageOptions: {
      globals: {
        ...globals.browser,
      },
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    rules: {
      // React Hooks recommended rules (but not React Compiler experimental ones)
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",

      // Allow constant exports for barrel files and shadcn/ui pattern
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],

      // Practical TypeScript rules
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-require-imports": "off",
    },
  },

  // Relax rules for UI component library (shadcn/ui pattern)
  {
    files: ["src/components/ui/**/*.tsx"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },

  // Relax rules for test files
  {
    files: ["src/**/*.test.ts", "src/**/*.test.tsx"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "no-constant-binary-expression": "off",
    },
  },
);
