// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Estado de la conexión Firebird Embedded (banner de setup en la UI). */
	dbHealth: () => __TAURI_INVOKE<DbHealth>("db_health"),
	createLocalBackup: (destPath: string) => typedError<string, AppError>(__TAURI_INVOKE("create_local_backup", { destPath })),
	listSpecies: () => typedError<Species[], AppError>(__TAURI_INVOKE("list_species")),
	listBreeds: (speciesId: number) => typedError<Breed[], AppError>(__TAURI_INVOKE("list_breeds", { speciesId })),
	listSampleTypes: () => typedError<SampleType[], AppError>(__TAURI_INVOKE("list_sample_types")),
	listAnalytes: () => typedError<Analyte[], AppError>(__TAURI_INVOKE("list_analytes")),
	/**  Catálogo de vacunas del esquema (Rabia, Polivalente, FeLV…). */
	listVaccineTypes: () => typedError<VaccineType[], AppError>(__TAURI_INVOKE("list_vaccine_types")),
	/**  Listado de propietarios (para facturación y búsquedas). */
	listOwners: (search: string | null) => typedError<Owner[], AppError>(__TAURI_INVOKE("list_owners", { search })),
	listPatients: (search: string | null) => typedError<Patient[], AppError>(__TAURI_INVOKE("list_patients", { search })),
	getPatient: (id: number) => typedError<{
	id: number,
	ownerId: number,
	speciesId: number,
	breedId: number | null,
	name: string,
	/**  M | F */
	sex: string,
	/**  YYYY-MM-DD */
	birthDate: string | null,
	neutered: boolean,
	color: string | null,
	microchip: string | null,
	active: boolean,
	notes: string | null,
	speciesName: string,
	breedName: string | null,
	ownerName: string,
	ownerPhone: string | null,
	/**  Calculada en SQL (DATEDIFF meses desde birth_date). */
	ageMonths: number,
} | null, AppError>(__TAURI_INVOKE("get_patient", { id })),
	createPatient: (input: CreatePatientInput) => typedError<Patient, AppError>(__TAURI_INVOKE("create_patient", { input })),
	getClinicalHistory: (patientId: number) => typedError<ClinicalHistory, AppError>(__TAURI_INVOKE("get_clinical_history", { patientId })),
	createConsultation: (input: CreateConsultationInput) => typedError<Consultation, AppError>(__TAURI_INVOKE("create_consultation", { input })),
	/**  Recepción de muestra analítica (trazabilidad: código M-YYYY-NNNN, estado RECIBIDA). */
	createSample: (input: CreateSampleInput) => typedError<Sample, AppError>(__TAURI_INVOKE("create_sample", { input })),
	/**
	 *  Carga un resultado de laboratorio; valida el rango de referencia por
	 *  especie/edad/sexo vía stored procedure y finaliza la muestra.
	 *  Invalida el cache de IA para esta muestra.
	 */
	registerLabResult: (input: RegisterResultInput) => typedError<LabResult, AppError>(__TAURI_INVOKE("register_lab_result", { input })),
	/**
	 *  Mesa de trabajo del laboratorio: listado global de muestras con filtros
	 *  opcionales por estado y búsqueda (código, paciente o propietario).
	 */
	listSamples: (status: string | null, search: string | null) => typedError<SampleListItem[], AppError>(__TAURI_INVOKE("list_samples", { status, search })),
	/**  Ficha completa de una muestra (con resultados) para el detalle del lab. */
	getSample: (id: number) => typedError<{
	id: number,
	/**  Código único de trazabilidad (M-YYYY-NNNN) */
	code: string,
	patientId: number,
	sampleTypeId: number,
	sampleTypeName: string,
	receivedAt: string,
	/**  RECIBIDA | EN_PROCESO | FINALIZADA | ANULADA */
	status: string,
	collectedBy: string | null,
	notes: string | null,
	results: LabResult[],
} | null, AppError>(__TAURI_INVOKE("get_sample", { id })),
	/**  Cambia el estado de una muestra (RECIBIDA→EN_PROCESO, →ANULADA). */
	setSampleStatus: (id: number, status: string) => typedError<Sample, AppError>(__TAURI_INVOKE("set_sample_status", { id, status })),
	/**  Configuración de la clínica (nombre, NIT, IVA, firma de reportes…). */
	getClinicSettings: () => typedError<ClinicSettings, AppError>(__TAURI_INVOKE("get_clinic_settings")),
	saveClinicSettings: (input: ClinicSettings) => typedError<ClinicSettings, AppError>(__TAURI_INVOKE("save_clinic_settings", { input })),
	/**
	 *  Copia el logo seleccionado a la carpeta de datos de la app y devuelve su
	 *  ruta. De este modo el logo persiste aunque se mueva/borre el original.
	 */
	importClinicLogo: (sourcePath: string) => typedError<string, AppError>(__TAURI_INVOKE("import_clinic_logo", { sourcePath })),
	/**
	 *  Inicia sesión verificando la contraseña (Argon2id) contra la tabla USERS.
	 *  La sesión es única: una app de escritorio con un operador a la vez.
	 * 
	 *  Protección contra fuerza bruta: tras 5 intentos fallidos consecutivos,
	 *  el login se bloquea por 5 minutos para ese usuario.
	 */
	login: (input: LoginInput) => typedError<SessionUser, AppError>(__TAURI_INVOKE("login", { input })),
	logout: () => typedError<null, AppError>(__TAURI_INVOKE("logout")),
	/**  Sesión activa (restaura la UI al reabrir la ventana). */
	getSession: () => typedError<{
	id: number,
	username: string,
	fullName: string,
	/**  ADMIN | VETERINARIO | AUXILIAR */
	role: string,
	/**  `true` si el usuario debe fijar una contraseña propia al iniciar sesión. */
	mustChangePassword: boolean,
} | null, AppError>(__TAURI_INVOKE("get_session")),
	/**  Genera el informe PDF de una muestra (con resultados) y devuelve la ruta. */
	generateClinicalReport: (sampleId: number) => typedError<ReportFile, AppError>(__TAURI_INVOKE("generate_clinical_report", { sampleId })),
	/**  Genera la fórmula médica (receta) de una consulta y devuelve la ruta. */
	generateFormulaMedica: (consultationId: number) => typedError<ReportFile, AppError>(__TAURI_INVOKE("generate_formula_medica", { consultationId })),
	/**  Genera el consentimiento informado de una cirugía programada. */
	generateConsentimiento: (surgeryId: number) => typedError<ReportFile, AppError>(__TAURI_INVOKE("generate_consentimiento", { surgeryId })),
	/**  Genera el comprobante de pago (recibo) de una factura. */
	generateReciboInvoice: (invoiceId: number) => typedError<ReportFile, AppError>(__TAURI_INVOKE("generate_recibo_invoice", { invoiceId })),
	/**  Genera el reporte/certificado quirúrgico de una cirugía. */
	generateCertificadoCirugia: (surgeryId: number) => typedError<ReportFile, AppError>(__TAURI_INVOKE("generate_certificado_cirugia", { surgeryId })),
	/**  Genera el certificado/carnet de vacunación de un paciente. */
	generateCarnetVacunacion: (patientId: number) => typedError<ReportFile, AppError>(__TAURI_INVOKE("generate_carnet_vacunacion", { patientId })),
	/**  Lista los informes ya generados (carpeta app_data/reports), más reciente primero. */
	listReports: () => typedError<ReportFile[], AppError>(__TAURI_INVOKE("list_reports")),
	/**  Abre un archivo de reporte PDF en el visor por defecto del sistema operativo. */
	openReportFile: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("open_report_file", { path })),
	/**  Listado de usuarios (sin hashes) — solo ADMIN. */
	listUsers: () => typedError<UserListItem[], AppError>(__TAURI_INVOKE("list_users")),
	/**
	 *  Crea un usuario con rol y contraseña inicial — solo ADMIN. El usuario
	 *  deberá cambiar la contraseña en su primer acceso (MUST_CHANGE_PASSWORD).
	 */
	createUser: (input: CreateUserInput) => typedError<UserListItem, AppError>(__TAURI_INVOKE("create_user", { input })),
	/**
	 *  Cambia la contraseña del usuario con la sesión activa. Verifica la
	 *  contraseña actual y limpia MUST_CHANGE_PASSWORD. Devuelve la sesión
	 *  actualizada.
	 */
	changePassword: (input: ChangePasswordInput) => typedError<SessionUser, AppError>(__TAURI_INVOKE("change_password", { input })),
	/**  Agenda: listado global de consultas con filtros por estado y búsqueda. */
	listConsultations: (status: string | null, search: string | null) => typedError<ConsultationListItem[], AppError>(__TAURI_INVOKE("list_consultations", { status, search })),
	/**  Agenda: completa o cancela una consulta pendiente. */
	setConsultationStatus: (id: number, status: string) => typedError<ConsultationListItem, AppError>(__TAURI_INVOKE("set_consultation_status", { id, status })),
	/**
	 *  Registra una vacuna/desparasitación atribuyéndola al veterinario de la
	 *  sesión activa. Dispara el refresco del historial clínico en el frontend.
	 */
	createVaccine: (input: CreateVaccineInput) => typedError<Vaccine, AppError>(__TAURI_INVOKE("create_vaccine", { input })),
	/**  Listado global de vacunación (búsqueda por paciente, propietario o vacuna). */
	listVaccines: (search: string | null) => typedError<VaccineListItem[], AppError>(__TAURI_INVOKE("list_vaccines", { search })),
	/**  Programa una cirugía atribuyéndola al veterinario de la sesión activa. */
	createSurgery: (input: CreateSurgeryInput) => typedError<Surgery, AppError>(__TAURI_INVOKE("create_surgery", { input })),
	/**  Agenda quirúrgica: listado con filtros por estado y búsqueda. */
	listSurgeries: (status: string | null, search: string | null) => typedError<Surgery[], AppError>(__TAURI_INVOKE("list_surgeries", { status, search })),
	/**  Cambia el estado de una cirugía (PROGRAMADA→EN_CURSO/COMPLETADA/CANCELADA). */
	setSurgeryStatus: (id: number, status: string) => typedError<Surgery, AppError>(__TAURI_INVOKE("set_surgery_status", { id, status })),
	/**  Emite una factura con items; calcula subtotal, IVA y total en Rust. */
	createInvoice: (input: CreateInvoiceInput) => typedError<Invoice, AppError>(__TAURI_INVOKE("create_invoice", { input })),
	/**  Listado de facturas con filtros por estado y búsqueda. */
	listInvoices: (status: string | null, search: string | null) => typedError<InvoiceListItem[], AppError>(__TAURI_INVOKE("list_invoices", { status, search })),
	/**  Ficha completa de una factura (con items). */
	getInvoice: (id: number) => typedError<{
	id: number,
	/**  Código único (FAC-000001…) */
	invoiceNumber: string,
	patientId: number | null,
	patientName: string | null,
	ownerId: number,
	ownerName: string,
	ownerPhone: string | null,
	consultationId: number | null,
	/**  YYYY-MM-DD HH:MM:SS */
	issueDate: string,
	subtotal: number | null,
	taxRate: number | null,
	taxAmount: number | null,
	total: number | null,
	/**  EMITIDA | PAGADA | ANULADA */
	status: string,
	paymentMethod: string | null,
	notes: string | null,
	items: InvoiceItem[],
} | null, AppError>(__TAURI_INVOKE("get_invoice", { id })),
	/**  Cambia el estado de una factura (EMITIDA→PAGADA/ANULADA, PAGADA→ANULADA). */
	setInvoiceStatus: (id: number, status: string) => typedError<Invoice, AppError>(__TAURI_INVOKE("set_invoice_status", { id, status })),
	/**
	 *  Métricas del panel de control: contadores, agenda de próximas citas y
	 *  cirugías, refuerzos de vacunación y últimas muestras.
	 */
	getDashboardStats: () => typedError<DashboardStats, AppError>(__TAURI_INVOKE("get_dashboard_stats")),
	/**
	 *  Lista el registro de auditoría con paginación (solo ADMIN).
	 *  Orden descendente (más reciente primero).
	 */
	listAuditLog: (limit: number | null, offset: number | null) => typedError<AuditLogEntry[], AppError>(__TAURI_INVOKE("list_audit_log", { limit, offset })),
	interpretLabResults: (sampleId: number) => typedError<string, AppError>(__TAURI_INVOKE("interpret_lab_results", { sampleId })),
	getPatientLabTrends: (patientId: number, analyteId: number) => typedError<TrendPoint[], AppError>(__TAURI_INVOKE("get_patient_lab_trends", { patientId, analyteId })),
};

/* Types */
export type Analyte = {
	id: number,
	code: string,
	name: string,
	unit: string | null,
	method: string | null,
};

/**  Error tipado de la app. Se serializa como `{ type, data }` para el frontend. */
export type AppError = { type: "Db"; data: string } | { type: "NotFound"; data: string } | { type: "Validation"; data: string } | { type: "Forbidden"; data: string } | { type: "Internal"; data: string };

/**  Fila del registro de auditoría (USER_AUDIT_LOG). */
export type AuditLogEntry = {
	id: number,
	userId: number | null,
	username: string,
	action: string,
	details: string | null,
	createdAt: string,
};

export type Breed = {
	id: number,
	speciesId: number,
	name: string,
};

export type ChangePasswordInput = {
	currentPassword: string,
	newPassword: string,
};

/**  Configuración de la clínica (tabla CLINIC_SETTINGS, claves planas). */
export type ClinicSettings = {
	clinicName: string,
	clinicNit: string,
	address: string | null,
	phone: string | null,
	city: string | null,
	logoPath: string | null,
	/**  IVA por defecto (%). */
	taxRate: number | null,
	currency: string,
	/**  GRAPHIC (imagen) o DIGITAL (PKCS#12). */
	signatureMode: string,
	vetName: string,
	vetLicense: string | null,
	groqApiKey: string | null,
};

/**  Agregado del historial clínico completo de un paciente. */
export type ClinicalHistory = {
	patient: Patient,
	owner: Owner | null,
	consultations: Consultation[],
	vaccines: Vaccine[],
	samples: Sample[],
};

export type Consultation = {
	id: number,
	patientId: number,
	veterinarianId: number | null,
	/**  YYYY-MM-DD HH:MM:SS */
	consultationDate: string,
	reason: string,
	anamnesis: string | null,
	physicalExam: string | null,
	diagnosis: string | null,
	treatmentPlan: string | null,
	status: string,
	veterinarianName: string | null,
};

/**  Fila del listado global de consultas (agenda) con datos del paciente unidos. */
export type ConsultationListItem = {
	id: number,
	patientId: number,
	patientName: string,
	speciesName: string,
	ownerName: string,
	/**  YYYY-MM-DD HH:MM:SS */
	consultationDate: string,
	reason: string,
	status: string,
	veterinarianName: string | null,
};

export type CreateConsultationInput = {
	patientId: number,
	consultationDate: string,
	reason: string,
	anamnesis: string | null,
	physicalExam: string | null,
	diagnosis: string | null,
	treatmentPlan: string | null,
	status: string,
};

export type CreateInvoiceInput = {
	patientId: number | null,
	ownerId: number,
	consultationId: number | null,
	/**  IVA por defecto (%), tomado de la configuración si no se envía. */
	taxRate: number | null,
	paymentMethod: string | null,
	notes: string | null,
	items: CreateInvoiceItemInput[],
};

export type CreateInvoiceItemInput = {
	description: string,
	quantity: number,
	unitPrice: number | null,
};

export type CreateOwnerInput = {
	documentType: string,
	documentNumber: string,
	fullName: string,
	phone: string | null,
	email: string | null,
	address: string | null,
	city: string | null,
};

export type CreatePatientInput = {
	owner: CreateOwnerInput,
	name: string,
	speciesId: number,
	breedId: number | null,
	sex: string,
	birthDate: string | null,
	neutered: boolean,
	color: string | null,
	microchip: string | null,
	notes: string | null,
};

export type CreateSampleInput = {
	patientId: number,
	sampleTypeId: number,
	receivedAt: string,
	collectedBy: string | null,
	notes: string | null,
};

export type CreateSurgeryInput = {
	patientId: number,
	surgeryType: string,
	scheduledAt: string,
	anesthesiaType: string | null,
	preoperativeNotes: string | null,
	postoperativeNotes: string | null,
};

export type CreateUserInput = {
	username: string,
	fullName: string,
	/**  ADMIN | VETERINARIO | AUXILIAR */
	role: string,
	/**  Contraseña inicial; el usuario deberá cambiarla en su primer acceso. */
	initialPassword: string,
};

/**  Entrada del registro de vacunación (insumo del formulario). */
export type CreateVaccineInput = {
	patientId: number,
	vaccineTypeId: number | null,
	vaccineName: string,
	dose: string | null,
	administeredAt: string,
	nextDoseAt: string | null,
	lot: string | null,
	manufacturer: string | null,
	notes: string | null,
};

/**
 *  Métricas del panel de control (dashboard) con las próximas citas,
 *  cirugías y refuerzos de vacunación de la agenda.
 */
export type DashboardStats = {
	patientsTotal: number,
	patientsActive: number,
	samplesTotal: number,
	samplesInProgress: number,
	samplesFinished: number,
	samplesCancelled: number,
	abnormalResults: number,
	consultationsPending: number,
	surgeriesProgrammed: number,
	/**  Refuerzos cuya fecha ya venció. */
	vaccinesDue: number,
	/**  Facturas emitidas sin pagar. */
	invoicesUnpaid: number,
	/**  Ingresos totales (facturas PAGADA). */
	revenueTotal: number | null,
	/**  Próximas consultas PENDIENTE (máx. 5). */
	upcomingConsultations: ConsultationListItem[],
	/**  Próximas cirugías PROGRAMADA/EN_CURSO (máx. 5). */
	upcomingSurgeries: Surgery[],
	/**  Próximos refuerzos de vacunación (máx. 5). */
	upcomingVaccines: VaccineListItem[],
	/**  Últimas muestras recibidas (máx. 5). */
	recentSamples: SampleListItem[],
};

export type DbHealth = {
	ok: boolean,
	message: string,
	dbPath: string,
	fbclientFound: boolean,
	fbclientPath: string,
	schemaVersion: number,
};

/**  Factura completa con items y datos del propietario/paciente unidos. */
export type Invoice = {
	id: number,
	/**  Código único (FAC-000001…) */
	invoiceNumber: string,
	patientId: number | null,
	patientName: string | null,
	ownerId: number,
	ownerName: string,
	ownerPhone: string | null,
	consultationId: number | null,
	/**  YYYY-MM-DD HH:MM:SS */
	issueDate: string,
	subtotal: number | null,
	taxRate: number | null,
	taxAmount: number | null,
	total: number | null,
	/**  EMITIDA | PAGADA | ANULADA */
	status: string,
	paymentMethod: string | null,
	notes: string | null,
	items: InvoiceItem[],
};

/**  Línea de detalle de una factura. */
export type InvoiceItem = {
	id: number,
	description: string,
	quantity: number,
	unitPrice: number | null,
	lineTotal: number | null,
};

/**  Fila del listado de facturas (sin items). */
export type InvoiceListItem = {
	id: number,
	invoiceNumber: string,
	ownerName: string,
	patientName: string | null,
	issueDate: string,
	total: number | null,
	/**  EMITIDA | PAGADA | ANULADA */
	status: string,
	paymentMethod: string | null,
	itemCount: number,
};

export type LabResult = {
	id: number,
	sampleId: number,
	analyteId: number,
	analyteName: string,
	unit: string | null,
	value: number | null,
	/**  BAJO | NORMAL | ALTO | SIN_RANGO (calculado por SP_VALIDATE_ANALYTICAL_RESULT) */
	status: string,
	refMin: number | null,
	refMax: number | null,
	analyzedAt: string | null,
};

export type LabResultChangedEvent = {
	sampleId: number,
	patientId: number,
};

export type LoginInput = {
	username: string,
	password: string,
};

export type Owner = {
	id: number,
	documentType: string,
	documentNumber: string,
	fullName: string,
	phone: string | null,
	email: string | null,
	address: string | null,
	city: string | null,
};

/**  Ficha de paciente con campos unidos (especie, raza, propietario, edad). */
export type Patient = {
	id: number,
	ownerId: number,
	speciesId: number,
	breedId: number | null,
	name: string,
	/**  M | F */
	sex: string,
	/**  YYYY-MM-DD */
	birthDate: string | null,
	neutered: boolean,
	color: string | null,
	microchip: string | null,
	active: boolean,
	notes: string | null,
	speciesName: string,
	breedName: string | null,
	ownerName: string,
	ownerPhone: string | null,
	/**  Calculada en SQL (DATEDIFF meses desde birth_date). */
	ageMonths: number,
};

export type RegisterResultInput = {
	sampleId: number,
	analyteId: number,
	value: number | null,
};

/**  Un informe PDF ya generado (listado de la carpeta app_data/reports). */
export type ReportFile = {
	/**  Ruta absoluta del archivo (para abrirlo con el visor del SO). */
	path: string,
	fileName: string,
	/**  Código de la muestra origen (derivado del nombre del archivo). */
	sampleCode: string,
	/**  YYYY-MM-DD HH:MM:SS (hora local de generación). */
	generatedAt: string,
};

export type Sample = {
	id: number,
	/**  Código único de trazabilidad (M-YYYY-NNNN) */
	code: string,
	patientId: number,
	sampleTypeId: number,
	sampleTypeName: string,
	receivedAt: string,
	/**  RECIBIDA | EN_PROCESO | FINALIZADA | ANULADA */
	status: string,
	collectedBy: string | null,
	notes: string | null,
	results: LabResult[],
};

export type SampleChangedEvent = {
	sampleId: number,
	patientId: number,
	status: string,
};

/**
 *  Fila de la "mesa de trabajo" del laboratorio: una muestra con los datos del
 *  paciente/propietario unidos (vista global, no por paciente).
 */
export type SampleListItem = {
	id: number,
	/**  Código único de trazabilidad (M-YYYY-NNNN) */
	code: string,
	patientId: number,
	patientName: string,
	ownerName: string,
	speciesName: string,
	sampleTypeId: number,
	sampleTypeName: string,
	receivedAt: string,
	/**  RECIBIDA | EN_PROCESO | FINALIZADA | ANULADA */
	status: string,
	collectedBy: string | null,
	notes: string | null,
	/**  Nº de resultados cargados (para el badge de progreso). */
	resultCount: number,
	/**  Nº de resultados fuera de rango (ALTO/BAJO) — alerta visual. */
	abnormalCount: number,
};

export type SampleType = {
	id: number,
	code: string,
	name: string,
};

/**  Usuario autenticado (sin hash de contraseña). */
export type SessionUser = {
	id: number,
	username: string,
	fullName: string,
	/**  ADMIN | VETERINARIO | AUXILIAR */
	role: string,
	/**  `true` si el usuario debe fijar una contraseña propia al iniciar sesión. */
	mustChangePassword: boolean,
};

export type Species = {
	id: number,
	code: string,
	name: string,
};

/**  Cirugía programada con datos del paciente unidos (agenda quirúrgica). */
export type Surgery = {
	id: number,
	patientId: number,
	patientName: string,
	speciesName: string,
	ownerName: string,
	ownerPhone: string | null,
	veterinarianId: number | null,
	veterinarianName: string | null,
	surgeryType: string,
	/**  YYYY-MM-DD HH:MM:SS */
	scheduledAt: string,
	anesthesiaType: string | null,
	preoperativeNotes: string | null,
	postoperativeNotes: string | null,
	/**  PROGRAMADA | EN_CURSO | COMPLETADA | CANCELADA */
	status: string,
};

export type TrendPoint = {
	date: string,
	value: number | null,
	refMin: number | null,
	refMax: number | null,
	status: string,
};

/**  Fila del listado de usuarios (nunca expone el hash). */
export type UserListItem = {
	id: number,
	username: string,
	fullName: string,
	/**  ADMIN | VETERINARIO | AUXILIAR */
	role: string,
	active: boolean,
	mustChangePassword: boolean,
	createdAt: string,
};

/**  Vacuna administrada a un paciente (con campos unidos para el listado global). */
export type Vaccine = {
	id: number,
	patientId: number,
	vaccineTypeId: number | null,
	vaccineName: string,
	dose: string | null,
	administeredAt: string,
	nextDoseAt: string | null,
	lot: string | null,
	manufacturer: string | null,
	veterinarianName: string | null,
	notes: string | null,
};

/**  Fila del listado global de vacunación (vista por paciente/propietario). */
export type VaccineListItem = {
	id: number,
	patientId: number,
	patientName: string,
	speciesName: string,
	ownerName: string,
	vaccineName: string,
	administeredAt: string,
	nextDoseAt: string | null,
	lot: string | null,
	manufacturer: string | null,
	veterinarianName: string | null,
};

export type VaccineType = {
	id: number,
	code: string,
	name: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

